import type { Content } from "./types";

export const en: Content = {
  meta: {
    title: "Sharply | Custom websites and web apps, by Noah Janssen",
    description:
      "Websites, shops and AI systems with the polish of a top studio, designed and built by one maker. After launch you change anything by simply asking.",
    localeTag: "en_GB",
  },
  nav: {
    links: [
      { href: "#studio", label: "About me" },
      { href: "#werk", label: "Work" },
      { href: "#diensten", label: "Services" },
      { href: "#prijzen", label: "Pricing" },
    ],
    cta: "Start a project",
    stickyButton: "Start a project",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    langLabel: "Language",
  },
  hero: {
    lineOne: "Custom websites",
    lineTwo: "for businesses.",
    body: "I design and build websites and web apps that bring in enquiries, with an assistant you use to change them yourself afterwards. You work directly with me.",
    primary: "Start a project",
    secondary: "See the prices",
    price: "From €1,800, excluding VAT",
    proof: "Online",
    imageAlt:
      "Glass orb with an iridescent sheen above a blue horizon in deep dark space",
  },
  manifesto: {
    title: "Design and build, from one maker",
    lead: "One maker, from the first idea to the last pixel.",
    body: [
      "I am Noah. I design and build websites and AI systems, from first sketch to launch. Design, code and imagery come from the same hand, and you can see it: everything fits together.",
      "You speak directly with the person making your project. Decisions are quick, the result stays consistent, and AI takes over the repetitive work, so my time goes into design and detail.",
      "I take on a limited number of projects at a time, so each one gets my full attention. My clients are business owners who see their online presence as an investment.",
    ],
    imageAlt: "Portrait of Noah Janssen",
    caption: "Noah Janssen, Roermond",
    stage: {
      role: "Designer and developer",
      chatTitle: "Assistant",
      chatQuestion: "Can I come by on Saturday?",
      chatAnswer: "Saturday at 11:00 is still free. Shall I book it for you?",
      chatInput: "Type a message",
      priceTitle: "Indication",
      priceRange: "€6,500 to €8,000",
      priceNote: "Studio, excluding VAT",
      checkoutTitle: "Checkout",
      checkoutTotal: "Total",
      checkoutAmount: "€125.00",
      checkoutPay: "Pay with iDEAL",
      live: "Live at yourcompany.com",
    },
  },
  services: {
    title: "What I make",
    lead: "Three things, done well: a site that brings in enquiries, an assistant that helps your customers and systems that take over the work.",
    items: [
      {
        key: "websites",
        title: "A website that brings in enquiries",
        body: "A design that builds trust and a site that loads in a flash. And when you need more: a complete web app with accounts, a database and stored data, like Renofloww.",
        points: ["Bespoke design", "Accounts and database", "Lightning fast on every screen"],
        image: "/images/service-websites-2.webp",
        alt: "A laptop and phone showing this site's homepage: the headline 'Websites die klanten winnen' beside a glass bubble",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "An assistant for your customers",
        body: "A smart assistant inside your own site that answers questions, books appointments and knows your information. Available day and night.",
        points: ["Knows your content", "Books appointments", "Works with your systems"],
        image: "/images/service-ai-chat-3.webp",
        alt: "A ceramics studio's site with an assistant beside it booking a workshop, and a notice that the appointment is booked",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "A shop that sells",
        body: "A store that feels like your brand. Payment, stock and shipping work the way you are used to, and the experience is entirely yours.",
        points: ["Designed around your products", "Cards and local payments", "Stock kept in sync"],
        image: "/images/service-webshop-2.webp",
        alt: "A laptop with a product page of a ceramics shop, a phone with the product overview and a shipping box with a bowl in it",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Systems that work together",
        body: "Calendar, mail, stock, invoices and CRM, joined into one smooth workflow. Whatever repeats simply runs itself.",
        points: ["Everything connected", "Work that runs itself", "Reporting to steer by"],
        image: "/images/service-integrations-3.webp",
        alt: "An order in the middle, connected to a calendar, mail, stock and accounting: one action, four systems updated",
        placeholder: true,
      },
      {
        key: "branding",
        title: "A brand with presence",
        body: "Logo, colour, typography and motion, brought together in guidelines your whole team works with.",
        points: ["Logo and identity", "Brand guidelines", "Animation and video"],
        image: "/images/service-branding-motion-2.webp",
        alt: "A brand identity on a table: a tote bag, letterhead, business cards and a coffee cup with the same mark, beside a colour card and a type card",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "Imagery and video on demand",
        body: "Campaign imagery and video in your brand style: created in a flash with AI and finished by hand where it counts.",
        points: ["Stills and video", "Campaign sets", "Consistent with your brand"],
        image: "/images/service-ai-content-2.webp",
        alt: "A screen with nine photos of the same mug and bowl in one consistent style, and a tablet with a vertical story and a video timeline",
        placeholder: true,
      },
    ],
    core: ["websites", "aiChat", "integrations"],
    more: "Also possible",
  },
  demo: {
    title: "Change your site by asking.",
    lead: "Every site I build comes with an assistant that knows it inside out. You say what you want changed, you see it happen, and you put it live yourself. A new opening time or a different headline takes a minute. Try it here.",
    note: "This is a demo of the principle. On a real project the assistant works with your content, your domain and your styling, and you decide what it may change.",
    tryTitle: "Try it yourself",
    badge: "Interactive demo",
    previewLabel: "The site changes here as you click",
    tryHint: "Click an instruction and watch the example site next to it change. Or type what you want different.",
    inputLabel: "Or type your own instruction",
    inputPlaceholder: "For example: make the headline bigger",
    send: "Run",
    reset: "Start over",
    unknownReply:
      "That instruction is not part of this demo. Pick one from the list above.",
    unpublishedNote: "Not published yet",
    commands: [
      {
        id: "headline",
        label: "Make the headline bigger",
        reply: "The headline is one size up.",
      },
      {
        id: "light",
        label: "Switch to the light theme",
        reply: "Light theme is on.",
      },
      {
        id: "shop",
        label: "Add a shop section",
        reply: "A shop section now sits under the headline.",
      },
      {
        id: "publish",
        label: "Publish",
        reply: "Published. The change is live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Ceramics from Amsterdam North",
      headlineBig: "Ceramics from Amsterdam North",
      body: "Small runs, thrown by hand and fired in our own kiln.",
      cta: "See the work",
      shopTitle: "Available now",
      shopItems: [
        { name: "Bowl, speckled white", price: "48" },
        { name: "Vase, deep blue", price: "125" },
        { name: "Plate, sand", price: "36" },
      ],
    },
    deploy: {
      building: "Publishing",
      live: "Live at",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "What you asked",
  },
  work: {
    title: "Work",
    lead: "Four projects that are online, each with its own face: from a brand site that brings in bookings to software with accounts and a database.",
    body: "More projects to follow.",
    conceptLabel: "Concept project",
    clientLabel: "Client project",
    ctaTitle: "Your project next?",
    ctaText: "Tell me what you have in mind and I will turn it into something special.",
    ctaButton: "Start a project",
    items: [
      {
        key: "liveweddingpaintings",
        title: "Live Wedding Paintings",
        discipline: "Brand, website and bookings",
        blurb:
          "The website of Sara van Heukelom, who paints weddings live. Brand, design, engineering and booking form all come from me.",
        image: "/images/showcase-liveweddingpaintings.webp",
        thumb: "/images/card-liveweddingpaintings.webp",
        alt: "The Live Wedding Paintings homepage: three paintings in gold frames beside the name in a decorative script",
        real: true,
      },
      {
        key: "renofloww",
        title: "Renofloww",
        discipline: "Web app with accounts and database",
        blurb:
          "A complete web app with real accounts and its own database: users sign in and their budget, planning, quotes and photos are stored per project. With an assistant that reads that data.",
        image: "/images/showcase-renofloww.webp",
        thumb: "/images/card-renofloww.webp",
        alt: "The Renofloww homepage: the headline 'Je verbouwing, eindelijk in één overzicht' above a week-by-week bathroom schedule",
        real: true,
        label: "Live product",
      },
      {
        key: "daalwerk",
        title: "Daalwerk",
        discipline: "Brand, website and assistant",
        blurb:
          "The site of an interior and architecture studio in Limburg. A house you watch change as you scroll, from shell to floor plan, and an assistant that gives a first direction for material and colour.",
        image: "/images/showcase-daalwerk.webp",
        thumb: "/images/card-daalwerk.webp",
        alt: "The Daalwerk homepage: a maquette of a courtyard farm beside the headline 'Verder bouwen op wat er staat'",
        real: true,
        label: "Own project",
      },
      {
        key: "flowdezk",
        title: "FlowDezk",
        discipline: "Redesign of a product site",
        blurb:
          "Software for translation agencies. One project you follow by scrolling, from quote to invoice, a price calculator and a request form that asks what a translation agency actually deals with.",
        image: "/images/showcase-flowdezk-en.webp",
        thumb: "/images/card-flowdezk-en.webp",
        alt: "The FlowDezk homepage on laptop and phone: 'Every project. From quote to invoice.' beside an example project",
        real: true,
        label: "Redesign",
      },
    ],
  },
  process: {
    title: "How I work",
    lead: "Four steps, from the first conversation to launch.",
    steps: [
      {
        title: "Listening",
        body: "I start with your business, your customers and your ambition. The result is a clear plan, in plain language.",
      },
      {
        title: "Designing",
        body: "You see the design before a line of code is written: direction, typography, colour and motion, built on your own content.",
      },
      {
        title: "Building",
        body: "I build to measure in code, not in a page builder. You follow along on a test address and look in every week.",
      },
      {
        title: "Going live",
        body: "I take care of the domain, the hosting and the speed. Then I show you how to make changes yourself, simply by asking.",
      },
    ],
  },
  contact: {
    title: "Tell me about your project",
    lead: "Answer a few short questions and build your own package. You see what it costs along the way, and at the end you take out whatever you can do without to stay inside your budget. Only marked fields are required.",
    progress: "Step {current} of {total}",
    optional: "optional",
    required: "This field is still empty",
    invalidEmail: "Please check your email address",
    invalidUrl: "Please check the link",
    pickOne: "Pick at least one option",
    tooShort: "Tell me a little more, at least {min} characters",
    consentRequired: "Please agree to be able to send this",
    next: "Continue",
    back: "Back",
    submit: "Send request",
    sending: "Sending",
    edit: "Edit",
    reviewTitle: "Everything at a glance",
    reviewIntro: "Check your request. If everything looks right, I receive it right away.",
    empty: "Not filled in",
    noDetails: "I have no follow-up questions for your choices. Feel free to continue.",
    selectPlaceholder: "Choose an option",
    filesHint: "Up to 3 files, 4 MB in total. PDF, image or Word.",
    filesAdd: "Add files",
    filesRemove: "Remove",
    filesTooBig: "These files are larger than 4 MB together",
    filesTooMany: "You can attach up to 3 files",
    filesType: "I cannot process this file type",
    successTitle: "Your request is in",
    successBody:
      "Thank you. I read your request personally and reply within two working days. Do check your spam folder, just in case.",
    againLabel: "Send another request",
    privacyLink: "Read my privacy statement",
    errorTitle: "Sending did not go through",
    errorBody:
      "Please try again in a moment, or email me directly at noah.janssen@sharply.nl.",
    price: {
      title: "An indication, from your answers",
      to: "to",
      vat: "Amounts exclude VAT.",
      packageTitle: "Your package",
      packageHint: "Take parts out or put them back. The price follows straight away.",
      budgetLabel: "My budget",
      budgetPick: "Pick your budget and I will show what fits.",
      budgetFits: "This package fits your budget.",
      budgetMaybe: "This package may just fit your budget.",
      budgetOver: "This package is {amount} over your budget.",
      fit: "Fit it to my budget",
      onePage: "Make it a single page",
      onePageBack: "Back to up to 5 pages",
      remove: "Remove",
      removeLabel: "Remove {item}",
      restore: "Put back",
      restoreAll: "Put everything back",
      removedTitle: "Removed",
      emptyPackage: "You removed everything. Put something back to see an indication.",
      floor: "The smallest version comes to {amount}. Below that? Email me and I will see what is possible.",
      floorMail: "Email me",
      monthlyLabel: "Care after launch",
      running: "Indication so far",
      perMonthShort: "a month",
      rush: "Delivered fast",
      perItem: { "website.languages": "Extra language", "webshop.payments": "Extra payment method", "ai-chat.channels": "Extra channel", "automation.tools": "Integration" },
      care: "Looking after it afterwards, {plan} plan: {price} a month.",
      plans: { basis: "Basis", groei: "Growth", volledig: "Complete" },
      open: "Part of what you want is bespoke. That is not in this indication yet.",
      note: "This is a direction, not a quote. After a half-hour introduction you receive a fixed price, for a smaller first step too.",
    },
    steps: [
      {
        id: "needs",
        title: "What you need",
        hint: "Pick everything that applies.",
        fields: [
          {
            id: "needs.needs",
            kind: "chips",
            multi: true,
            required: true,
            label: "What can I help with",
            options: [
              { id: "website", label: "A new website or web app" },
              { id: "webshop", label: "An online shop" },
              { id: "ai-chat", label: "An AI assistant for my customers" },
              { id: "automation", label: "Automate manual work" },
              { id: "branding", label: "A new brand or identity" },
              { id: "motion", label: "Motion and video" },
              { id: "ai-content", label: "Imagery and content with AI" },
              { id: "other", label: "Something else" },
            ],
          },
        ],
      },
      {
        id: "about",
        title: "About you",
        hint: "So I understand who I am building for.",
        fields: [
          {
            id: "about.company",
            kind: "text",
            required: true,
            half: true,
            label: "Company name",
            autoComplete: "organization",
          },
          {
            id: "about.website",
            kind: "url",
            half: true,
            label: "Current website",
            placeholder: "yourcompany.com",
            autoComplete: "url",
          },
          {
            id: "about.role",
            kind: "text",
            half: true,
            label: "Your role",
            placeholder: "For example owner or marketing manager",
            autoComplete: "organization-title",
          },
          {
            id: "about.industry",
            kind: "select",
            half: true,
            label: "Industry",
            options: [
              { id: "retail", label: "Retail and e-commerce" },
              { id: "hospitality", label: "Hospitality and travel" },
              { id: "health", label: "Health and wellbeing" },
              { id: "finance", label: "Finance and business services" },
              { id: "tech", label: "Software and tech" },
              { id: "education", label: "Education" },
              { id: "public", label: "Non-profit and public sector" },
              { id: "creative", label: "Creative and media" },
              { id: "industry", label: "Industry and logistics" },
              { id: "other", label: "Other" },
            ],
          },
          {
            id: "about.size",
            kind: "chips",
            label: "How big is the company",
            options: [
              { id: "solo", label: "Just me" },
              { id: "2-10", label: "2 to 10" },
              { id: "11-50", label: "11 to 50" },
              { id: "51-250", label: "51 to 250" },
              { id: "250+", label: "More than 250" },
            ],
          },
          {
            id: "about.situation",
            kind: "chips",
            label: "Where are you now",
            options: [
              { id: "new", label: "Starting from scratch" },
              { id: "old", label: "There is something, but it is outdated" },
              { id: "ok", label: "It works, but could be far better" },
              { id: "rebrand", label: "We are rebranding" },
            ],
          },
        ],
      },
      {
        id: "goals",
        title: "Goal",
        hint: "What the project should do for you.",
        fields: [
          {
            id: "goals.goals",
            kind: "chips",
            multi: true,
            required: true,
            label: "What do you want to achieve",
            options: [
              { id: "leads", label: "More enquiries" },
              { id: "sales", label: "Sell online" },
              { id: "time", label: "Automate work" },
              { id: "brand", label: "A stronger brand" },
              { id: "launch", label: "Launch something new" },
              { id: "replace", label: "Replace something outdated" },
              { id: "support", label: "Help customers better" },
              { id: "scale", label: "Grow internationally" },
            ],
          },
          {
            id: "goals.project",
            kind: "area",
            required: true,
            min: 20,
            rows: 4,
            label: "What is it about",
            placeholder:
              "What kind of business do you run, what do you want to build and what is not working now?",
          },
          {
            id: "goals.audience",
            kind: "area",
            rows: 2,
            label: "Who is it for",
            placeholder: "Who are your customers and what do they expect?",
          },
          {
            id: "goals.success",
            kind: "area",
            rows: 2,
            label: "How will I know it worked",
            placeholder:
              "For example twice as many enquiries, or ten hours a week less manual work.",
          },
        ],
      },
      {
        id: "details",
        title: "Details",
        hint: "Only questions about what you picked. Skip anything you do not know yet.",
        fields: [],
      },
      {
        id: "style",
        title: "Style and material",
        hint: "Show me what you like and what you already have.",
        fields: [
          {
            id: "style.mood",
            kind: "chips",
            multi: true,
            label: "Which mood fits you",
            options: [
              { id: "minimal", label: "Calm and minimal" },
              { id: "bold", label: "Bold and big" },
              { id: "futuristic", label: "Futuristic" },
              { id: "playful", label: "Playful" },
              { id: "editorial", label: "Editorial and refined" },
              { id: "corporate", label: "Corporate and trustworthy" },
              { id: "warm", label: "Warm and human" },
              { id: "dark", label: "Dark" },
              { id: "light", label: "Light" },
            ],
          },
          {
            id: "style.references",
            kind: "area",
            rows: 3,
            label: "Sites and brands you like",
            placeholder: "Paste links and tell me what you like about them.",
          },
          {
            id: "style.dislikes",
            kind: "area",
            rows: 2,
            label: "What do you want to avoid",
            placeholder: "Styles, colours or things you rule out up front.",
          },
          {
            id: "style.assets",
            kind: "chips",
            multi: true,
            label: "What already exists",
            options: [
              { id: "logo", label: "Logo" },
              { id: "guidelines", label: "Brand guidelines" },
              { id: "fonts", label: "Fonts" },
              { id: "photos", label: "Photography" },
              { id: "copy", label: "Copy" },
              { id: "video", label: "Video" },
              { id: "none", label: "Nothing yet" },
            ],
          },
          {
            id: "style.files",
            kind: "files",
            label: "Attachments",
            hint: "A brief, logo or example helps me reply faster.",
          },
        ],
      },
      {
        id: "plan",
        title: "Budget and timing",
        hint: "A rough direction is enough.",
        fields: [
          {
            id: "plan.budget",
            kind: "chips",
            required: true,
            label: "Budget",
            options: [
              { id: "lt-2500", label: "Up to 2,500 euro" },
              { id: "2500-5k", label: "2,500 to 5,000 euro" },
              { id: "5-10k", label: "5,000 to 10,000 euro" },
              { id: "10-25k", label: "10,000 to 25,000 euro" },
              { id: "gt-25k", label: "More than 25,000 euro" },
              { id: "unknown", label: "Not sure yet" },
            ],
          },
          {
            id: "plan.timeline",
            kind: "chips",
            required: true,
            label: "When do you want to be live",
            options: [
              { id: "asap", label: "As soon as possible" },
              { id: "quarter", label: "Within three months" },
              { id: "half-year", label: "Within six months" },
              { id: "exploring", label: "Still exploring" },
            ],
          },
          {
            id: "plan.deadline",
            kind: "date",
            half: true,
            label: "Hard deadline",
            hint: "For example a launch or an event.",
          },
          {
            id: "plan.maintenance",
            kind: "chips",
            label: "Who looks after it afterwards",
            options: [
              { id: "self", label: "We do" },
              { id: "studio", label: "Sharply keeps helping" },
              { id: "unsure", label: "Not sure yet" },
            ],
          },
          {
            id: "plan.decision",
            kind: "chips",
            label: "Who decides",
            options: [
              { id: "me", label: "I decide" },
              { id: "team", label: "A small team" },
              { id: "board", label: "Management or several parties" },
            ],
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        hint: "So I can reply.",
        fields: [
          {
            id: "contact.name",
            kind: "text",
            required: true,
            half: true,
            label: "Name",
            autoComplete: "name",
          },
          {
            id: "contact.email",
            kind: "email",
            required: true,
            half: true,
            label: "Email address",
            autoComplete: "email",
          },
          {
            id: "contact.phone",
            kind: "tel",
            half: true,
            label: "Phone number",
            autoComplete: "tel",
          },
          {
            id: "contact.source",
            kind: "select",
            half: true,
            label: "How did you find me",
            options: [
              { id: "search", label: "Search engine" },
              { id: "social", label: "Social media" },
              { id: "linkedin", label: "LinkedIn" },
              { id: "referral", label: "Through someone" },
              { id: "other", label: "Other" },
            ],
          },
          {
            id: "contact.preferred",
            kind: "chips",
            label: "How would you like to hear from me",
            options: [
              { id: "mail", label: "By email" },
              { id: "phone", label: "By phone" },
              { id: "video", label: "Video call" },
            ],
          },
          {
            id: "contact.consent",
            kind: "consent",
            required: true,
            label:
              "I agree that Sharply uses my details to respond to my request.",
          },
        ],
      },
      {
        id: "review",
        title: "Review",
        hint: "One last look before it goes.",
        fields: [],
      },
    ],
    detailGroups: [
      {
        need: "website",
        title: "Website or web app",
        fields: [
          {
            id: "website.pages",
            kind: "chips",
            label: "How big will it be",
            options: [
              { id: "1", label: "One page" },
              { id: "1-5", label: "2 to 5 pages" },
              { id: "6-15", label: "6 to 15" },
              { id: "16-40", label: "16 to 40" },
              { id: "40+", label: "More than 40" },
              { id: "unknown", label: "Not sure" },
            ],
          },
          {
            id: "website.languages",
            kind: "chips",
            multi: true,
            label: "In which languages",
            options: [
              { id: "nl", label: "Dutch" },
              { id: "en", label: "English" },
              { id: "de", label: "German" },
              { id: "fr", label: "French" },
              { id: "more", label: "More languages" },
            ],
          },
          {
            id: "website.editing",
            kind: "chips",
            label: "Who edits the content",
            options: [
              { id: "self", label: "We do" },
              { id: "talk", label: "By asking the site" },
              { id: "studio", label: "Sharply" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "website.features",
            kind: "chips",
            multi: true,
            label: "What should be in it",
            options: [
              { id: "blog", label: "Blog or news" },
              { id: "cases", label: "Portfolio or case studies" },
              { id: "account", label: "Logins and accounts" },
              { id: "booking", label: "Appointments or bookings" },
              { id: "forms", label: "Smart forms" },
              { id: "search", label: "Search" },
              { id: "animation", label: "Advanced animation or 3D" },
              { id: "crm", label: "CRM or email integration" },
            ],
          },
        ],
      },
      {
        need: "webshop",
        title: "Online shop",
        fields: [
          {
            id: "webshop.products",
            kind: "chips",
            label: "How many products",
            options: [
              { id: "lt-25", label: "Up to 25" },
              { id: "25-250", label: "25 to 250" },
              { id: "250-2500", label: "250 to 2,500" },
              { id: "2500+", label: "More than 2,500" },
            ],
          },
          {
            id: "webshop.platform",
            kind: "chips",
            label: "Is there a shop already",
            options: [
              { id: "shopify", label: "Shopify" },
              { id: "woo", label: "WooCommerce" },
              { id: "none", label: "Not yet" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "webshop.payments",
            kind: "chips",
            multi: true,
            label: "Which payment methods",
            options: [
              { id: "ideal", label: "iDEAL" },
              { id: "cards", label: "Credit card" },
              { id: "paypal", label: "PayPal" },
              { id: "bnpl", label: "Buy now, pay later" },
              { id: "invoice", label: "On invoice" },
            ],
          },
          {
            id: "webshop.shipping",
            kind: "chips",
            label: "Where do you ship",
            options: [
              { id: "nl", label: "Netherlands only" },
              { id: "eu", label: "Europe" },
              { id: "world", label: "Worldwide" },
              { id: "digital", label: "Digital products" },
            ],
          },
        ],
      },
      {
        need: "ai-chat",
        title: "AI chat or agent",
        fields: [
          {
            id: "ai-chat.channels",
            kind: "chips",
            multi: true,
            label: "Where should it run",
            options: [
              { id: "site", label: "On the website" },
              { id: "whatsapp", label: "WhatsApp" },
              { id: "email", label: "Email" },
              { id: "app", label: "In an app" },
              { id: "internal", label: "Internal, for staff" },
            ],
          },
          {
            id: "ai-chat.jobs",
            kind: "chips",
            multi: true,
            label: "What should it do",
            options: [
              { id: "faq", label: "Answer questions" },
              { id: "booking", label: "Book appointments" },
              { id: "leads", label: "Qualify leads" },
              { id: "orders", label: "Give order status" },
              { id: "knowledge", label: "Make internal knowledge searchable" },
            ],
          },
          {
            id: "ai-chat.sources",
            kind: "chips",
            multi: true,
            label: "Where does its knowledge come from",
            options: [
              { id: "site", label: "Our website" },
              { id: "docs", label: "Documents and PDFs" },
              { id: "helpdesk", label: "Helpdesk or tickets" },
              { id: "crm", label: "CRM or database" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "ai-chat.handoff",
            kind: "chips",
            label: "Should a person be able to take over",
            options: [
              { id: "yes", label: "Yes, to a team member" },
              { id: "no", label: "No, fully automatic" },
              { id: "unsure", label: "Not sure" },
            ],
          },
        ],
      },
      {
        need: "automation",
        title: "Integrations and automation",
        fields: [
          {
            id: "automation.tools",
            kind: "chips",
            multi: true,
            label: "Which systems do you use",
            options: [
              { id: "google", label: "Google Workspace" },
              { id: "microsoft", label: "Microsoft 365" },
              { id: "hubspot", label: "HubSpot" },
              { id: "salesforce", label: "Salesforce" },
              { id: "accounting", label: "Exact or Moneybird" },
              { id: "shop", label: "Shopify or WooCommerce" },
              { id: "chat", label: "Slack or Teams" },
              { id: "other", label: "Other tools" },
            ],
          },
          {
            id: "automation.what",
            kind: "area",
            rows: 3,
            label: "What should happen by itself",
            placeholder:
              "For example: new enquiries land in the CRM automatically and a quote is ready.",
          },
          {
            id: "automation.volume",
            kind: "chips",
            label: "How often does it happen",
            options: [
              { id: "weekly", label: "A few times a week" },
              { id: "daily", label: "Daily" },
              { id: "hundreds", label: "Hundreds a day" },
              { id: "unknown", label: "Not sure" },
            ],
          },
        ],
      },
      {
        need: "branding",
        title: "Branding",
        fields: [
          {
            id: "branding.current",
            kind: "chips",
            label: "What is there now",
            options: [
              { id: "none", label: "Nothing yet" },
              { id: "logo", label: "Just a logo" },
              { id: "full", label: "A full identity" },
              { id: "redo", label: "Start over" },
            ],
          },
          {
            id: "branding.deliverables",
            kind: "chips",
            multi: true,
            label: "What do you need",
            options: [
              { id: "logo", label: "Logo" },
              { id: "colour", label: "Colour and typography" },
              { id: "guidelines", label: "Brand guidelines" },
              { id: "templates", label: "Social and print templates" },
              { id: "packaging", label: "Packaging" },
              { id: "signage", label: "Signage or interiors" },
            ],
          },
        ],
      },
      {
        need: "motion",
        title: "Motion and video",
        fields: [
          {
            id: "motion.kinds",
            kind: "chips",
            multi: true,
            label: "What kind of motion",
            options: [
              { id: "logo", label: "Logo animation" },
              { id: "social", label: "Social video" },
              { id: "product", label: "Product video" },
              { id: "explainer", label: "Explainer video" },
              { id: "web", label: "Motion for the website" },
            ],
          },
          {
            id: "motion.amount",
            kind: "chips",
            label: "How much",
            options: [
              { id: "one", label: "One piece" },
              { id: "few", label: "Two to five" },
              { id: "series", label: "An ongoing series" },
            ],
          },
        ],
      },
      {
        need: "ai-content",
        title: "AI content",
        fields: [
          {
            id: "ai-content.kinds",
            kind: "chips",
            multi: true,
            label: "What kind of content",
            options: [
              { id: "images", label: "Images" },
              { id: "video", label: "Video" },
              { id: "animation", label: "Animation" },
              { id: "campaigns", label: "Full campaign sets" },
            ],
          },
          {
            id: "ai-content.volume",
            kind: "chips",
            label: "How much",
            options: [
              { id: "lt-10", label: "Up to 10 pieces" },
              { id: "10-50", label: "10 to 50" },
              { id: "50+", label: "More than 50" },
              { id: "ongoing", label: "Ongoing, monthly" },
            ],
          },
        ],
      },
      {
        need: "other",
        title: "Something else",
        fields: [
          {
            id: "other.what",
            kind: "area",
            rows: 3,
            label: "Tell me what you have in mind",
            placeholder: "Describe it as concretely as you can.",
          },
        ],
      },
    ],
  },
  pricing: {
    title: "What it costs",
    lead: "Three packages. Pick one, or build your own package in the form.",
    vatNote:
      "All amounts exclude VAT. After an introduction you receive a fixed price, tailored to exactly what you need.",
    websitesTitle: "Websites, one time",
    tiers: [
      {
        name: "Spark",
        price: 1800,
        from: true,
        body: "One strong page that shows what you do and how people reach you. The fastest way to be online professionally.",
        points: ["One page", "Custom design", "Contact form", "Launch on your own domain"],
      },
      {
        name: "Start",
        price: 3500,
        body: "A refined brand site that is entirely yours.",
        points: ["Up to 5 pages", "One language", "Custom design", "Contact form and launch"],
      },
      {
        name: "Studio",
        price: 6500,
        recommended: true,
        body: "For when there is more to tell: more pages, more movement and two languages.",
        points: ["Up to 12 pages", "Two languages", "Custom animation", "Booking or forms"],
      },
    ],
    careTitle: "After launch",
    careLead:
      "Hosting, updates and the assistant you use to make changes yourself. You have one point of contact and no content system to learn.",
    careMore: "More changes or new sections? Growth is €199 and Complete €399 a month.",
    beyondTitle: "Bigger than Studio?",
    beyondText: "A web app with accounts, a platform of your own or software like Renofloww: quoted, from €11,500.",
    plans: [
      { name: "Basis", price: 99, body: "Hosting, updates and the assistant for small changes." },
      { name: "Growth", price: 199, recommended: true, body: "More changes, a roomier assistant and small new pieces." },
      { name: "Complete", price: 399, body: "New sections and integrations as well. For shops and platforms." },
    ],
    perMonth: "a month",
    from: "from",
    recommended: "Recommended",
    otherTitle: "Other services",
    other: [
      { name: "AI assistant in an existing site", price: "from €3,500" },
      { name: "Integrations and automation", price: "from €2,000" },
      { name: "Webshop", price: "from €9,000" },
      { name: "Brand identity", price: "€2,500 to €6,000" },
    ],
    ctaTitle: "Not sure yet what you need?",
    ctaText: "Fill in the form and see an indication straight away, based on your own answers.",
    ctaButton: "Get an indication",
    ctaMail: "Rather talk first? Email me",
  },
  faq: {
    title: "Frequently asked questions",
    items: [
      {
        question: "What does a website cost?",
        answer: "A Spark page starts at €1,800 and a full brand site at €3,500, excluding VAT. After a half-hour introduction you receive a fixed price, with no surprises afterwards. In the form you build your own package and see straight away what each part costs.",
      },
      {
        question: "How long does it take?",
        answer: "A Start site is typically online within four to six weeks, a Studio site within six to ten. After our introduction you receive a schedule with fixed milestones.",
      },
      {
        question: "Who owns the website and the code?",
        answer: "You do. You receive all source files and your own hosting and domain account. The site is entirely yours, and stays that way.",
      },
      {
        question: "What if I do not like the design?",
        answer: "You see and approve the design before the build begins, and we refine it until it is exactly right. That way you know what you are getting.",
      },
      {
        question: "I am not technical. Can I change things myself?",
        answer: "Absolutely, that is what the assistant is for. You say what you want changed, such as a text, a photo or an opening time, you see it happen, and you put it live yourself. There is no content system to learn.",
      },
      {
        question: "Who writes the copy and supplies the imagery?",
        answer: "You supply the facts and the imagery you have, and I write persuasive copy around them. Where imagery is missing, I create it with AI and finish it by hand.",
      },
      {
        question: "How and when do I pay?",
        answer: "A part at the start and the rest at delivery. The exact split is in your quote up front.",
      },
    ],
  },
  privacy: {
    title: "Privacy statement",
    updated: "Last updated: 1 October 2026",
    sections: [
      {
        title: "Who I am",
        body: [
          "Sharply is a sole proprietorship of Noah Janssen, Scheidingsweg 2, 6045 CR Roermond, the Netherlands, Chamber of Commerce number 76336840. I am responsible for how your data is handled.",
          "Questions? Email noah.janssen@sharply.nl.",
        ],
      },
      {
        title: "What data I handle",
        body: [
          "Only what you fill in yourself in the request form: your name, email address, phone number (if you enter one), company name, your answers to the questions and the files you attach (up to three, 4 MB in total).",
          "If you email me directly, I keep that email.",
        ],
      },
      {
        title: "What I use it for",
        body: [
          "To answer your request and prepare a quote. Not for advertising or newsletters, unless you ask for them yourself.",
          "The basis is that you get in touch yourself and I take steps at your request before we enter into an agreement.",
        ],
      },
      {
        title: "Cookies and tracking",
        body: [
          "This site uses no tracking or analytics cookies and therefore shows no cookie banner.",
          "There is one functional cookie, sharply-lang, which remembers your language choice for a year. Your browser also remembers during your visit that you have seen the loading screen. Neither contains personal data.",
        ],
      },
      {
        title: "Who I share it with",
        body: [
          "With Resend, which sends the emails from the form, and with Vercel, where the site runs. They process data on my behalf and may do so outside the European Economic Area.",
          "I never sell your data and do not pass it on to anyone else.",
        ],
      },
      {
        title: "How long I keep it",
        body: [
          "Requests that do not lead to a project I delete within twelve months of receiving them.",
          "Data I need for the administration of a project I keep for seven years, the period the law requires.",
        ],
      },
      {
        title: "Your rights",
        body: [
          "You may see your data, have it corrected or deleted, object to the handling of it and take it with you. Email me and I will reply within four weeks.",
          "If you disagree, you can lodge a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).",
        ],
      },
    ],
  },
  footer: {
    privacy: "Privacy",
    contactTitle: "Get started",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply is the studio of Noah Janssen, in Roermond, the Netherlands.",
    // From the Dutch trade register (sole proprietorship, head office). VAT number still to add.
    placeholders: ["Chamber of Commerce 76336840", "Scheidingsweg 2", "6045 CR Roermond"],
    socialTitle: "Follow",
    socialNote: "Channels coming soon.",
    rights: "All rights reserved.",
  },
};
