import type { Content } from "./types";

export const en: Content = {
  meta: {
    title: "Sharply, design studio for brands, websites and AI systems",
    description:
      "Sharply designs brands and builds high-end websites, online shops and AI systems you run yourself.",
    localeTag: "en_GB",
  },
  nav: {
    links: [
      { href: "#studio", label: "Studio" },
      { href: "#diensten", label: "Services" },
      { href: "#demo", label: "Demo" },
      { href: "#werkwijze", label: "Process" },
    ],
    cta: "Start a project",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    langLabel: "Language",
  },
  hero: {
    lineOne: "Sharply designed.",
    lineTwo: "Intelligently built.",
    body: "We build brands, websites and AI systems for companies that would rather not look like everyone else.",
    primary: "Start a project",
    secondary: "See the services",
    imageAlt:
      "Glass orb with an iridescent sheen above a blue horizon in deep dark space",
  },
  manifesto: {
    title: "The hand stays in it",
    lead: "AI makes it faster. The decisions stay ours.",
    body: [
      "We draw, write and direct the work ourselves. AI comes in where it raises the bar: a hundred variants in an afternoon, imagery that used to be out of budget, code that does exactly what it should.",
      "So what you see is not a button someone pressed. It is craft with an engine under it.",
    ],
    imageAlt:
      "Smooth glass orb resting on layers of hand-torn paper with visible fibres",
  },
  services: {
    title: "What we make",
    lead: "From a brand that holds up to a system that keeps running while you sleep.",
    items: [
      {
        key: "websites",
        title: "Websites and web apps",
        body: "From a site that lands to a platform with logins, a database and a dashboard. Built to load fast and last for years.",
        points: ["Designed from scratch", "Database and logins", "Edit your own copy"],
        image: "/images/service-websites.webp",
        alt: "Layered frosted glass panels catching blue rim light",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "AI chat and agents",
        body: "An assistant inside your own site that helps your customers, answers questions, books appointments and drives your systems. Trained on your information.",
        points: ["Trained on your content", "Books appointments", "Talks to your systems"],
        image: "/images/service-ai-chat.webp",
        alt: "Small glass sphere in a frosted card with a ribbon of blue light",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "Online shops",
        body: "Selling through a shop that feels like a brand instead of a template. Payments, stock and shipping work the way you expect.",
        points: ["Designed for your brand", "Cards and local payments", "Stock kept in sync"],
        image: "/images/service-webshop.webp",
        alt: "Translucent glass cubes stacked like parcels",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Integrations and automation",
        body: "Your systems joined up: calendar, mail, stock, invoices, CRM. Set up properly once, then it runs without you.",
        points: ["Systems connected", "Work that runs itself", "Reporting you can trust"],
        image: "/images/service-integrations.webp",
        alt: "Glass spheres connected by thin glowing blue threads",
        placeholder: true,
      },
      {
        key: "branding",
        title: "Branding and motion",
        body: "Logo, colour, typography and moving image. A brand that sounds the same everywhere, with guidelines your team can actually use.",
        points: ["Logo and identity", "Brand guidelines", "Animation and video"],
        image: "/images/service-branding-motion.webp",
        alt: "Twisting ribbon of liquid glass and chrome with motion blur",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "AI content",
        body: "Imagery, video and animation for campaigns and social. Generated where it can be, finished by hand where it counts.",
        points: ["Stills and video", "Campaign sets", "Consistent with your brand"],
        image: "/images/service-ai-content.webp",
        alt: "Glass prism splitting light into floating translucent frames",
        placeholder: true,
      },
    ],
  },
  demo: {
    title: "Say what you want. The site adapts.",
    lead: "This is how the sites we build work: you ask for a change, you see it straight away and you put it live. Try it here.",
    note: "This is a demo of the idea, not of your own site. On a real project this is wired to your content and your domain.",
    tryTitle: "Try it yourself",
    tryHint: "Click an instruction, or type your own. You see it happen on the right.",
    inputLabel: "Or type your own instruction",
    inputPlaceholder: "For example: make the headline bigger",
    send: "Run",
    reset: "Start over",
    unknownReply:
      "I do not know that one in this demo. Try one of the instructions above.",
    unpublishedNote: "Not published yet",
    commands: [
      {
        id: "headline",
        label: "Make the headline bigger",
        reply: "The headline is one size up.",
      },
      {
        id: "light",
        label: "Switch to the light theme",
        reply: "Light theme is on.",
      },
      {
        id: "shop",
        label: "Add a shop section",
        reply: "A shop section now sits under the headline.",
      },
      {
        id: "publish",
        label: "Publish",
        reply: "Published. The change is live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Ceramics from Amsterdam North",
      headlineBig: "Ceramics from Amsterdam North",
      body: "Small runs, thrown by hand and fired in our own kiln.",
      cta: "See the work",
      shopTitle: "Available now",
      shopItems: [
        { name: "Bowl, speckled white", price: "48" },
        { name: "Vase, deep blue", price: "125" },
        { name: "Plate, sand", price: "36" },
      ],
    },
    deploy: {
      building: "Publishing",
      live: "Live at",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "What you asked",
  },
  work: {
    title: "Work",
    lead: "We are keeping these places free for real projects.",
    body: "Sharply has only just started under this name. As soon as the first projects ship, they will sit here with imagery, approach and results. We are not putting invented case studies in the meantime.",
    badge: "To be filled in",
    slots: [
      { title: "Project one", discipline: "Brand and website" },
      { title: "Project two", discipline: "Online shop" },
      { title: "Project three", discipline: "AI system" },
    ],
  },
  process: {
    title: "How it goes",
    lead: "Four phases, from the first conversation to a site that is online.",
    steps: [
      {
        title: "Listening",
        body: "We start with your business, your customers and what is going wrong now. That turns into a plan you can follow, without jargon.",
      },
      {
        title: "Designing",
        body: "You see the design before a line of code exists. Direction, typography, colour and motion, built on your own content.",
      },
      {
        title: "Building",
        body: "We build it in code, not in a page builder. You follow along on a test address and can look over our shoulder every week.",
      },
      {
        title: "Going live",
        body: "We handle the domain, the hosting and the speed. Then we show you how to make changes yourself, simply by asking for them.",
      },
    ],
  },
  contact: {
    title: "Tell us what you want to build",
    lead: "Four short steps. Noah replies within two working days.",
    steps: [
      { title: "What you need", hint: "Pick everything that applies." },
      { title: "Your project", hint: "The more you tell us, the sharper our reply." },
      { title: "Budget and timing", hint: "A rough direction is enough." },
      { title: "Your details", hint: "So we can get back to you." },
    ],
    needsLabel: "What can we help with",
    needs: [
      { id: "website", label: "Website or web app" },
      { id: "webshop", label: "Online shop" },
      { id: "ai-chat", label: "AI chat or agent" },
      { id: "automation", label: "Integrations and automation" },
      { id: "branding", label: "Branding" },
      { id: "motion", label: "Motion and video" },
      { id: "ai-content", label: "AI content" },
      { id: "other", label: "Something else" },
    ],
    projectLabel: "What is it about",
    projectPlaceholder:
      "What kind of business do you run, what do you want to achieve and what is not working now?",
    referencesLabel: "Sites you like",
    referencesPlaceholder: "Paste links here, or describe the style you are after.",
    budgetLabel: "Budget",
    budgets: [
      { id: "lt-5k", label: "Up to 5,000 euro" },
      { id: "5-15k", label: "5,000 to 15,000 euro" },
      { id: "15-40k", label: "15,000 to 40,000 euro" },
      { id: "gt-40k", label: "More than 40,000 euro" },
      { id: "unknown", label: "Not sure yet" },
    ],
    timelineLabel: "When do you want to be live",
    timelines: [
      { id: "asap", label: "As soon as possible" },
      { id: "quarter", label: "Within three months" },
      { id: "half-year", label: "Within six months" },
      { id: "exploring", label: "Still exploring" },
    ],
    nameLabel: "Name",
    emailLabel: "Email address",
    companyLabel: "Company",
    phoneLabel: "Phone number",
    optional: "optional",
    next: "Continue",
    back: "Back",
    submit: "Send request",
    sending: "Sending",
    progress: "Step {current} of {total}",
    successTitle: "Your request is in",
    successBody:
      "Noah reads it personally and replies within two working days. Do check your spam folder.",
    againLabel: "Send another request",
    errorTitle: "Sending did not work",
    errorBody:
      "Please try again, or email noah.janssen@sharply.nl directly.",
    required: "This field is still empty",
    invalidEmail: "Please check your email address",
    pickOne: "Pick at least one option",
    tooShort: "Tell us a little more, at least ten characters",
  },
  footer: {
    contactTitle: "Get started",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply, a design studio in the Netherlands.",
    placeholders: [
      "Chamber of Commerce number to follow",
      "VAT number to follow",
      "Address to follow",
    ],
    socialTitle: "Follow",
    socialNote: "Channels coming soon.",
    rights: "All rights reserved.",
  },
};
