import type { Content } from "./types";

export const en: Content = {
  meta: {
    title: "Sharply | Agency-level websites, built by Noah Janssen",
    description:
      "Websites, shops and AI systems at agency level, designed and built by one maker. After launch you change your site yourself by talking to it.",
    localeTag: "en_GB",
  },
  nav: {
    links: [
      { href: "#studio", label: "About me" },
      { href: "#diensten", label: "Services" },
      { href: "#demo", label: "Demo" },
      { href: "#werkwijze", label: "Process" },
      { href: "#prijzen", label: "Pricing" },
    ],
    cta: "Start a project",
    stickyButton: "Start a project",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    langLabel: "Language",
  },
  hero: {
    lineOne: "A website at",
    lineTwo: "agency level.",
    body: "I design and build it myself, for business owners who want to grow. You talk to me, not to a team. And afterwards you change it by talking to it.",
    primary: "Start a project",
    secondary: "See the prices",
    imageAlt:
      "Glass orb with an iridescent sheen above a blue horizon in deep dark space",
  },
  manifesto: {
    title: "Agency quality, without the agency",
    lead: "The level of a large agency, with the maker on the line.",
    body: [
      "I am Noah. I design and build websites and AI systems, entirely myself: design, code and imagery. That is how I make sites at the level large marketing agencies advertise with: designed for you, written in code, fast, and finished down to the details.",
      "The difference is not the quality but the invoice. At an agency you pay for account managers, project leads, an office and the hours four people spend keeping each other informed. With me you talk to the person making it, and AI does the work that repeats.",
      "I deliberately take on a limited number of projects at a time, so you have my full attention. I work with business owners who want to invest in a site that works for them.",
    ],
    imageAlt: "Portrait of Noah Janssen",
    caption: "Noah Janssen, Roermond",
  },
  services: {
    title: "What I make",
    lead: "From a brand that holds up to a system that keeps running while you sleep.",
    items: [
      {
        key: "websites",
        title: "A site that brings in customers",
        body: "Does your site look dated, or bring in too few enquiries? I design and build a new one: fast, fully yours, and with logins and a database when you need more.",
        points: ["Designed from scratch", "Fast on every screen", "Edit your own copy"],
        image: "/images/service-websites.webp",
        alt: "A web page as layered glass panels: a menu bar, a large headline and a row of cards, floating in depth",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "An assistant that helps your customers",
        body: "Do you answer the same questions every day? An assistant in your own site does it for you, books appointments and knows your information.",
        points: ["Trained on your content", "Books appointments", "Talks to your systems"],
        image: "/images/service-ai-chat.webp",
        alt: "Glass chat bubbles stacked above each other, one glowing blue, with a glass sphere beside them as the assistant",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "A shop that sells",
        body: "Want to sell online without it looking like a stock store? A shop that feels like your brand, with payment, stock and shipping working the way you are used to.",
        points: ["Designed for your brand", "Cards and local payments", "Stock kept in sync"],
        image: "/images/service-webshop.webp",
        alt: "Three glass product cards holding bottles, the middle one lit, with a glass shopping bag in front",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Less manual work, more time",
        body: "Do you retype things from one program into another? I connect calendar, mail, stock, invoices and CRM so it carries on by itself.",
        points: ["Systems connected", "Work that runs itself", "Reporting you can trust"],
        image: "/images/service-integrations.webp",
        alt: "Five glass app tiles for calendar, mail, stock, charts and settings, wired to a central disc by glowing cables",
        placeholder: true,
      },
      {
        key: "branding",
        title: "A brand that sticks",
        body: "Does your brand look slightly different everywhere? Logo, colour, typography and moving image, with guidelines your team can move forward with.",
        points: ["Logo and identity", "Brand guidelines", "Animation and video"],
        image: "/images/service-branding-motion.webp",
        alt: "A glass medallion carrying a mark, surrounded by colour swatches and specimen plates, with a ribbon of liquid glass around it",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "Imagery and video without a shoot",
        body: "Need fresh visuals for campaigns and social all the time? I make them with AI where that works, and finish them by hand where it counts.",
        points: ["Stills and video", "Campaign sets", "Consistent with your brand"],
        image: "/images/service-ai-content.webp",
        alt: "Floating glass picture frames with a play button, one of them forming out of a cloud of blue particles",
        placeholder: true,
      },
    ],
  },
  demo: {
    title: "Your site stays yours. After launch as well.",
    lead: "Every site I build comes with an assistant that knows it. You say what you want changed, you see it happen, and you put it live yourself. No complicated content system, no waiting on an agency, no invoice for changing an opening time. Try it here.",
    note: "This is a demo of the idea, not of your own site. On a real project it is wired to your content, your domain and your styling, and you decide what may and may not be changed.",
    tryTitle: "Try it yourself",
    tryHint: "Click an instruction, or type your own. You see it happen in the preview.",
    inputLabel: "Or type your own instruction",
    inputPlaceholder: "For example: make the headline bigger",
    send: "Run",
    reset: "Start over",
    unknownReply:
      "I do not know that one in this demo. Try one of the instructions above.",
    unpublishedNote: "Not published yet",
    commands: [
      {
        id: "headline",
        label: "Make the headline bigger",
        reply: "The headline is one size up.",
      },
      {
        id: "light",
        label: "Switch to the light theme",
        reply: "Light theme is on.",
      },
      {
        id: "shop",
        label: "Add a shop section",
        reply: "A shop section now sits under the headline.",
      },
      {
        id: "publish",
        label: "Publish",
        reply: "Published. The change is live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Ceramics from Amsterdam North",
      headlineBig: "Ceramics from Amsterdam North",
      body: "Small runs, thrown by hand and fired in our own kiln.",
      cta: "See the work",
      shopTitle: "Available now",
      shopItems: [
        { name: "Bowl, speckled white", price: "48" },
        { name: "Vase, deep blue", price: "125" },
        { name: "Plate, sand", price: "36" },
      ],
    },
    deploy: {
      building: "Publishing",
      live: "Live at",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "What you asked",
  },
  work: {
    title: "Work",
    lead: "My first client project, from design to launch.",
    body: "More projects are coming soon.",
    conceptLabel: "Concept project",
    clientLabel: "Client project",
    ctaTitle: "Your project here?",
    ctaText: "Tell me what you want to build and your work will sit here soon.",
    ctaButton: "Start a project",
    items: [
      {
        key: "liveweddingpaintings",
        title: "Live Wedding Paintings",
        discipline: "Brand, website and bookings",
        blurb:
          "The site of Sara van Heukelom, who paints weddings live. Made by me from the first design to the booking form.",
        image: "/images/project-liveweddingpaintings.webp",
        alt: "Laptop and phone showing the Live Wedding Paintings website: paintings in gold frames on a warm, light background",
        real: true,
      },
    ],
  },
  process: {
    title: "How it goes",
    lead: "Four phases, from the first conversation to a site that is online.",
    steps: [
      {
        title: "Listening",
        body: "I start with your business, your customers and what is going wrong now. That turns into a plan you can follow, without jargon.",
      },
      {
        title: "Designing",
        body: "You see the design before a line of code exists. Direction, typography, colour and motion, built on your own content.",
      },
      {
        title: "Building",
        body: "I build it in code, not in a page builder. You follow along on a test address and can look over my shoulder every week.",
      },
      {
        title: "Going live",
        body: "I handle the domain, the hosting and the speed. Then I show you how to make changes yourself, simply by asking for them.",
      },
    ],
  },
  contact: {
    title: "Tell me what you want to build",
    lead: "Answer a few questions and you see a price indication at the end, straight away. The more you fill in, the sharper it is. Only marked fields are required, and you can always go back.",
    progress: "Step {current} of {total}",
    optional: "optional",
    required: "This field is still empty",
    invalidEmail: "Please check your email address",
    invalidUrl: "Please check the link",
    pickOne: "Pick at least one option",
    tooShort: "Tell me a little more, at least {min} characters",
    consentRequired: "Please agree to be able to send this",
    next: "Continue",
    back: "Back",
    submit: "Send request",
    sending: "Sending",
    edit: "Edit",
    reviewTitle: "Everything at a glance",
    reviewIntro: "Check your request. If it all looks right, it goes to me.",
    empty: "Not filled in",
    noDetails: "I have no follow-up questions for what you picked. Feel free to continue.",
    selectPlaceholder: "Choose an option",
    filesHint: "Up to 3 files, 4 MB in total. PDF, image or Word.",
    filesAdd: "Add files",
    filesRemove: "Remove",
    filesTooBig: "These files are larger than 4 MB together",
    filesTooMany: "You can attach up to 3 files",
    filesType: "I do not accept this file type",
    successTitle: "Your request is in",
    successBody:
      "I read it personally and reply within two working days. Do check your spam folder.",
    againLabel: "Send another request",
    privacyLink: "Read my privacy statement",
    errorTitle: "Sending did not work",
    errorBody:
      "Please try again, or email noah.janssen@sharply.nl directly.",
    price: {
      title: "An indication, from your answers",
      to: "to",
      vat: "Amounts exclude VAT.",
      driversTitle: "What sets this range",
      care: "Looking after it afterwards, {plan} plan: {price} a month.",
      plans: { basis: "Basis", groei: "Growth", volledig: "Complete" },
      open: "You also picked something a form cannot price, so that is not in here yet.",
      note: "This is a direction, not a quote. Half an hour on a call and I know what it really is, and then you get a fixed price. If it does not fit your budget, say so: there is nearly always a smaller first step.",
    },
    steps: [
      {
        id: "needs",
        title: "What you need",
        hint: "Pick everything that applies.",
        fields: [
          {
            id: "needs.needs",
            kind: "chips",
            multi: true,
            required: true,
            label: "What can I help with",
            options: [
              { id: "website", label: "A new website or web app" },
              { id: "webshop", label: "An online shop" },
              { id: "ai-chat", label: "An AI assistant for my customers" },
              { id: "automation", label: "Automate manual work" },
              { id: "branding", label: "A new brand or identity" },
              { id: "motion", label: "Motion and video" },
              { id: "ai-content", label: "Imagery and content with AI" },
              { id: "other", label: "Something else" },
            ],
          },
        ],
      },
      {
        id: "about",
        title: "About you",
        hint: "So I understand who I am building for.",
        fields: [
          {
            id: "about.company",
            kind: "text",
            required: true,
            half: true,
            label: "Company name",
            autoComplete: "organization",
          },
          {
            id: "about.website",
            kind: "url",
            half: true,
            label: "Current website",
            placeholder: "yourcompany.com",
            autoComplete: "url",
          },
          {
            id: "about.role",
            kind: "text",
            half: true,
            label: "Your role",
            placeholder: "For example owner or marketing manager",
            autoComplete: "organization-title",
          },
          {
            id: "about.industry",
            kind: "select",
            half: true,
            label: "Industry",
            options: [
              { id: "retail", label: "Retail and e-commerce" },
              { id: "hospitality", label: "Hospitality and travel" },
              { id: "health", label: "Health and wellbeing" },
              { id: "finance", label: "Finance and business services" },
              { id: "tech", label: "Software and tech" },
              { id: "education", label: "Education" },
              { id: "public", label: "Non-profit and public sector" },
              { id: "creative", label: "Creative and media" },
              { id: "industry", label: "Industry and logistics" },
              { id: "other", label: "Other" },
            ],
          },
          {
            id: "about.size",
            kind: "chips",
            label: "How big is the company",
            options: [
              { id: "solo", label: "Just me" },
              { id: "2-10", label: "2 to 10" },
              { id: "11-50", label: "11 to 50" },
              { id: "51-250", label: "51 to 250" },
              { id: "250+", label: "More than 250" },
            ],
          },
          {
            id: "about.situation",
            kind: "chips",
            label: "Where are you now",
            options: [
              { id: "new", label: "Starting from scratch" },
              { id: "old", label: "There is something, but it is outdated" },
              { id: "ok", label: "It works, but could be far better" },
              { id: "rebrand", label: "We are rebranding" },
            ],
          },
        ],
      },
      {
        id: "goals",
        title: "Goal",
        hint: "What the project should do for you.",
        fields: [
          {
            id: "goals.goals",
            kind: "chips",
            multi: true,
            required: true,
            label: "What do you want to achieve",
            options: [
              { id: "leads", label: "More enquiries" },
              { id: "sales", label: "Sell online" },
              { id: "time", label: "Automate work" },
              { id: "brand", label: "A stronger brand" },
              { id: "launch", label: "Launch something new" },
              { id: "replace", label: "Replace something outdated" },
              { id: "support", label: "Help customers better" },
              { id: "scale", label: "Grow internationally" },
            ],
          },
          {
            id: "goals.project",
            kind: "area",
            required: true,
            min: 20,
            rows: 4,
            label: "What is it about",
            placeholder:
              "What kind of business do you run, what do you want to build and what is not working now?",
          },
          {
            id: "goals.audience",
            kind: "area",
            rows: 2,
            label: "Who is it for",
            placeholder: "Who are your customers and what do they expect?",
          },
          {
            id: "goals.success",
            kind: "area",
            rows: 2,
            label: "How will I know it worked",
            placeholder:
              "For example twice as many enquiries, or ten hours a week less manual work.",
          },
        ],
      },
      {
        id: "details",
        title: "Details",
        hint: "Only questions about what you picked. Skip anything you do not know yet.",
        fields: [],
      },
      {
        id: "style",
        title: "Style and material",
        hint: "Show me what you like and what you already have.",
        fields: [
          {
            id: "style.mood",
            kind: "chips",
            multi: true,
            label: "Which mood fits you",
            options: [
              { id: "minimal", label: "Calm and minimal" },
              { id: "bold", label: "Bold and big" },
              { id: "futuristic", label: "Futuristic" },
              { id: "playful", label: "Playful" },
              { id: "editorial", label: "Editorial and refined" },
              { id: "corporate", label: "Corporate and trustworthy" },
              { id: "warm", label: "Warm and human" },
              { id: "dark", label: "Dark" },
              { id: "light", label: "Light" },
            ],
          },
          {
            id: "style.references",
            kind: "area",
            rows: 3,
            label: "Sites and brands you like",
            placeholder: "Paste links and tell me what you like about them.",
          },
          {
            id: "style.dislikes",
            kind: "area",
            rows: 2,
            label: "What do you want to avoid",
            placeholder: "Styles, colours or things you rule out up front.",
          },
          {
            id: "style.assets",
            kind: "chips",
            multi: true,
            label: "What already exists",
            options: [
              { id: "logo", label: "Logo" },
              { id: "guidelines", label: "Brand guidelines" },
              { id: "fonts", label: "Fonts" },
              { id: "photos", label: "Photography" },
              { id: "copy", label: "Copy" },
              { id: "video", label: "Video" },
              { id: "none", label: "Nothing yet" },
            ],
          },
          {
            id: "style.files",
            kind: "files",
            label: "Attachments",
            hint: "A brief, logo or example helps me reply faster.",
          },
        ],
      },
      {
        id: "plan",
        title: "Budget and timing",
        hint: "A rough direction is enough.",
        fields: [
          {
            id: "plan.budget",
            kind: "chips",
            required: true,
            label: "Budget",
            options: [
              { id: "lt-5k", label: "Up to 5,000 euro" },
              { id: "5-15k", label: "5,000 to 15,000 euro" },
              { id: "15-40k", label: "15,000 to 40,000 euro" },
              { id: "gt-40k", label: "More than 40,000 euro" },
              { id: "unknown", label: "Not sure yet" },
            ],
          },
          {
            id: "plan.timeline",
            kind: "chips",
            required: true,
            label: "When do you want to be live",
            options: [
              { id: "asap", label: "As soon as possible" },
              { id: "quarter", label: "Within three months" },
              { id: "half-year", label: "Within six months" },
              { id: "exploring", label: "Still exploring" },
            ],
          },
          {
            id: "plan.deadline",
            kind: "date",
            half: true,
            label: "Hard deadline",
            hint: "For example a launch or an event.",
          },
          {
            id: "plan.maintenance",
            kind: "chips",
            label: "Who looks after it afterwards",
            options: [
              { id: "self", label: "We do" },
              { id: "studio", label: "Sharply keeps helping" },
              { id: "unsure", label: "Not sure yet" },
            ],
          },
          {
            id: "plan.decision",
            kind: "chips",
            label: "Who decides",
            options: [
              { id: "me", label: "I decide" },
              { id: "team", label: "A small team" },
              { id: "board", label: "Management or several parties" },
            ],
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        hint: "So I can reply.",
        fields: [
          {
            id: "contact.name",
            kind: "text",
            required: true,
            half: true,
            label: "Name",
            autoComplete: "name",
          },
          {
            id: "contact.email",
            kind: "email",
            required: true,
            half: true,
            label: "Email address",
            autoComplete: "email",
          },
          {
            id: "contact.phone",
            kind: "tel",
            half: true,
            label: "Phone number",
            autoComplete: "tel",
          },
          {
            id: "contact.source",
            kind: "select",
            half: true,
            label: "How did you find me",
            options: [
              { id: "search", label: "Search engine" },
              { id: "social", label: "Social media" },
              { id: "linkedin", label: "LinkedIn" },
              { id: "referral", label: "Through someone" },
              { id: "other", label: "Other" },
            ],
          },
          {
            id: "contact.preferred",
            kind: "chips",
            label: "How would you like to hear from me",
            options: [
              { id: "mail", label: "By email" },
              { id: "phone", label: "By phone" },
              { id: "video", label: "Video call" },
            ],
          },
          {
            id: "contact.consent",
            kind: "consent",
            required: true,
            label:
              "I agree that Sharply uses my details to respond to my request.",
          },
        ],
      },
      {
        id: "review",
        title: "Review",
        hint: "One last look before it goes.",
        fields: [],
      },
    ],
    detailGroups: [
      {
        need: "website",
        title: "Website or web app",
        fields: [
          {
            id: "website.pages",
            kind: "chips",
            label: "How big will it be",
            options: [
              { id: "1-5", label: "1 to 5 pages" },
              { id: "6-15", label: "6 to 15" },
              { id: "16-40", label: "16 to 40" },
              { id: "40+", label: "More than 40" },
              { id: "unknown", label: "Not sure" },
            ],
          },
          {
            id: "website.languages",
            kind: "chips",
            multi: true,
            label: "In which languages",
            options: [
              { id: "nl", label: "Dutch" },
              { id: "en", label: "English" },
              { id: "de", label: "German" },
              { id: "fr", label: "French" },
              { id: "more", label: "More languages" },
            ],
          },
          {
            id: "website.editing",
            kind: "chips",
            label: "Who edits the content",
            options: [
              { id: "self", label: "We do" },
              { id: "talk", label: "By asking the site" },
              { id: "studio", label: "Sharply" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "website.features",
            kind: "chips",
            multi: true,
            label: "What should be in it",
            options: [
              { id: "blog", label: "Blog or news" },
              { id: "cases", label: "Portfolio or case studies" },
              { id: "account", label: "Logins and accounts" },
              { id: "booking", label: "Appointments or bookings" },
              { id: "forms", label: "Smart forms" },
              { id: "search", label: "Search" },
              { id: "animation", label: "Advanced animation or 3D" },
              { id: "crm", label: "CRM or email integration" },
            ],
          },
        ],
      },
      {
        need: "webshop",
        title: "Online shop",
        fields: [
          {
            id: "webshop.products",
            kind: "chips",
            label: "How many products",
            options: [
              { id: "lt-25", label: "Up to 25" },
              { id: "25-250", label: "25 to 250" },
              { id: "250-2500", label: "250 to 2,500" },
              { id: "2500+", label: "More than 2,500" },
            ],
          },
          {
            id: "webshop.platform",
            kind: "chips",
            label: "Is there a shop already",
            options: [
              { id: "shopify", label: "Shopify" },
              { id: "woo", label: "WooCommerce" },
              { id: "none", label: "Not yet" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "webshop.payments",
            kind: "chips",
            multi: true,
            label: "Which payment methods",
            options: [
              { id: "ideal", label: "iDEAL" },
              { id: "cards", label: "Credit card" },
              { id: "paypal", label: "PayPal" },
              { id: "bnpl", label: "Buy now, pay later" },
              { id: "invoice", label: "On invoice" },
            ],
          },
          {
            id: "webshop.shipping",
            kind: "chips",
            label: "Where do you ship",
            options: [
              { id: "nl", label: "Netherlands only" },
              { id: "eu", label: "Europe" },
              { id: "world", label: "Worldwide" },
              { id: "digital", label: "Digital products" },
            ],
          },
        ],
      },
      {
        need: "ai-chat",
        title: "AI chat or agent",
        fields: [
          {
            id: "ai-chat.channels",
            kind: "chips",
            multi: true,
            label: "Where should it run",
            options: [
              { id: "site", label: "On the website" },
              { id: "whatsapp", label: "WhatsApp" },
              { id: "email", label: "Email" },
              { id: "app", label: "In an app" },
              { id: "internal", label: "Internal, for staff" },
            ],
          },
          {
            id: "ai-chat.jobs",
            kind: "chips",
            multi: true,
            label: "What should it do",
            options: [
              { id: "faq", label: "Answer questions" },
              { id: "booking", label: "Book appointments" },
              { id: "leads", label: "Qualify leads" },
              { id: "orders", label: "Give order status" },
              { id: "knowledge", label: "Make internal knowledge searchable" },
            ],
          },
          {
            id: "ai-chat.sources",
            kind: "chips",
            multi: true,
            label: "Where does its knowledge come from",
            options: [
              { id: "site", label: "Our website" },
              { id: "docs", label: "Documents and PDFs" },
              { id: "helpdesk", label: "Helpdesk or tickets" },
              { id: "crm", label: "CRM or database" },
              { id: "unsure", label: "Not sure" },
            ],
          },
          {
            id: "ai-chat.handoff",
            kind: "chips",
            label: "Should a person be able to take over",
            options: [
              { id: "yes", label: "Yes, to a team member" },
              { id: "no", label: "No, fully automatic" },
              { id: "unsure", label: "Not sure" },
            ],
          },
        ],
      },
      {
        need: "automation",
        title: "Integrations and automation",
        fields: [
          {
            id: "automation.tools",
            kind: "chips",
            multi: true,
            label: "Which systems do you use",
            options: [
              { id: "google", label: "Google Workspace" },
              { id: "microsoft", label: "Microsoft 365" },
              { id: "hubspot", label: "HubSpot" },
              { id: "salesforce", label: "Salesforce" },
              { id: "accounting", label: "Exact or Moneybird" },
              { id: "shop", label: "Shopify or WooCommerce" },
              { id: "chat", label: "Slack or Teams" },
              { id: "other", label: "Other tools" },
            ],
          },
          {
            id: "automation.what",
            kind: "area",
            rows: 3,
            label: "What should happen by itself",
            placeholder:
              "For example: new enquiries land in the CRM automatically and a quote is ready.",
          },
          {
            id: "automation.volume",
            kind: "chips",
            label: "How often does it happen",
            options: [
              { id: "weekly", label: "A few times a week" },
              { id: "daily", label: "Daily" },
              { id: "hundreds", label: "Hundreds a day" },
              { id: "unknown", label: "Not sure" },
            ],
          },
        ],
      },
      {
        need: "branding",
        title: "Branding",
        fields: [
          {
            id: "branding.current",
            kind: "chips",
            label: "What is there now",
            options: [
              { id: "none", label: "Nothing yet" },
              { id: "logo", label: "Just a logo" },
              { id: "full", label: "A full identity" },
              { id: "redo", label: "Start over" },
            ],
          },
          {
            id: "branding.deliverables",
            kind: "chips",
            multi: true,
            label: "What do you need",
            options: [
              { id: "logo", label: "Logo" },
              { id: "colour", label: "Colour and typography" },
              { id: "guidelines", label: "Brand guidelines" },
              { id: "templates", label: "Social and print templates" },
              { id: "packaging", label: "Packaging" },
              { id: "signage", label: "Signage or interiors" },
            ],
          },
        ],
      },
      {
        need: "motion",
        title: "Motion and video",
        fields: [
          {
            id: "motion.kinds",
            kind: "chips",
            multi: true,
            label: "What kind of motion",
            options: [
              { id: "logo", label: "Logo animation" },
              { id: "social", label: "Social video" },
              { id: "product", label: "Product video" },
              { id: "explainer", label: "Explainer video" },
              { id: "web", label: "Motion for the website" },
            ],
          },
          {
            id: "motion.amount",
            kind: "chips",
            label: "How much",
            options: [
              { id: "one", label: "One piece" },
              { id: "few", label: "Two to five" },
              { id: "series", label: "An ongoing series" },
            ],
          },
        ],
      },
      {
        need: "ai-content",
        title: "AI content",
        fields: [
          {
            id: "ai-content.kinds",
            kind: "chips",
            multi: true,
            label: "What kind of content",
            options: [
              { id: "images", label: "Images" },
              { id: "video", label: "Video" },
              { id: "animation", label: "Animation" },
              { id: "campaigns", label: "Full campaign sets" },
            ],
          },
          {
            id: "ai-content.volume",
            kind: "chips",
            label: "How much",
            options: [
              { id: "lt-10", label: "Up to 10 pieces" },
              { id: "10-50", label: "10 to 50" },
              { id: "50+", label: "More than 50" },
              { id: "ongoing", label: "Ongoing, monthly" },
            ],
          },
        ],
      },
      {
        need: "other",
        title: "Something else",
        fields: [
          {
            id: "other.what",
            kind: "area",
            rows: 3,
            label: "Tell me what you have in mind",
            placeholder: "Describe it as concretely as you can.",
          },
        ],
      },
    ],
  },
  pricing: {
    title: "What it costs",
    lead: "Agency level, without the agency overhead. These are guide prices, so you do not have to guess.",
    vatNote:
      "All amounts exclude VAT. After a conversation you get a fixed price, and you never pay for what you do not need.",
    websitesTitle: "Websites, one time",
    tiers: [
      {
        name: "Start",
        price: 3500,
        body: "A sharp brand site that is properly yours.",
        points: ["Up to 5 pages", "One language", "Your own design, no template", "Form and live"],
      },
      {
        name: "Studio",
        price: 6500,
        recommended: true,
        body: "Where most companies land: more pages, more movement, two languages.",
        points: ["Up to 12 pages", "Two languages", "Custom animation", "Booking or forms"],
      },
      {
        name: "Signature",
        price: 11500,
        from: true,
        body: "As extensive as this site itself, with everything that comes with it.",
        points: ["Custom interaction and animation", "Login and database", "Connections to your systems", "An assistant of your own for your customers"],
      },
    ],
    careTitle: "After launch, the site stays yours",
    careLead:
      "Every site comes with an assistant you use to make changes yourself, plus hosting and updates. No content system to learn, no middleman to call.",
    plans: [
      { name: "Basis", price: 99, body: "Hosting, updates and the assistant for small changes." },
      { name: "Growth", price: 199, recommended: true, body: "More changes, a roomier assistant and small new pieces." },
      { name: "Complete", price: 399, body: "New sections and integrations as well. For shops and platforms." },
    ],
    perMonth: "a month",
    from: "from",
    recommended: "Recommended",
    otherTitle: "Other services",
    other: [
      { name: "Brand identity", price: "€2,500 to €6,000" },
      { name: "Webshop", price: "from €9,000" },
      { name: "AI assistant in an existing site", price: "from €3,500" },
      { name: "Integrations and automation", price: "from €2,000" },
      { name: "Motion and video", price: "from €1,200" },
      { name: "AI content", price: "from €900" },
    ],
    ctaTitle: "Not sure what you need?",
    ctaText: "Fill in the form and you see an indication straight away, based on your own answers.",
    ctaButton: "Get an indication",
    ctaMail: "Rather talk first? Email me",
  },
  faq: {
    title: "Questions you may have",
    items: [
      {
        question: "What does a website cost?",
        answer: "The packages are above and start at €3,500, excluding VAT. After half an hour on a call you get a fixed price. If €3,500 is more than you want to spend, I am not the right choice: a template site gets you online faster and cheaper.",
      },
      {
        question: "How long does it take?",
        answer: "A Start site is usually online within four to six weeks, a Studio site within six to ten. After the first conversation you get a schedule that is true, not one that sounds good.",
      },
      {
        question: "Who owns the website and the code?",
        answer: "You do. You get the source files and your own hosting and domain account, so you are never stuck with me.",
      },
      {
        question: "What if I do not like the design?",
        answer: "You see the design before I write a line of code, and you approve it first. That way I never build on a design you did not want.",
      },
      {
        question: "I am not technical. Can I change it myself?",
        answer: "Yes, that is what the assistant is for. You say what you want changed, such as a text, a photo or an opening time, you see it happen, and you put it live yourself. There is no content system to learn.",
      },
      {
        question: "Who writes the copy and supplies the imagery?",
        answer: "You supply the facts and the images you have, and I turn them into sharp copy. Where imagery is missing, I make it with AI or finish it by hand.",
      },
      {
        question: "How and when do I pay?",
        answer: "A part at the start, the rest at delivery. The exact split is in your quote, so you know where you stand up front.",
      },
    ],
  },
  privacy: {
    title: "Privacy statement",
    updated: "Last updated: 1 October 2026",
    sections: [
      {
        title: "Who I am",
        body: [
          "Sharply is a sole proprietorship of Noah Janssen, Scheidingsweg 2, 6045 CR Roermond, the Netherlands, Chamber of Commerce number 76336840. I am responsible for how your data is handled.",
          "Questions? Email noah.janssen@sharply.nl.",
        ],
      },
      {
        title: "What data I handle",
        body: [
          "Only what you fill in yourself in the request form: your name, email address, phone number (if you enter one), company name, your answers to the questions and the files you attach (up to three, 4 MB in total).",
          "If you email me directly, I keep that email.",
        ],
      },
      {
        title: "What I use it for",
        body: [
          "To answer your request and prepare a quote. Not for advertising or newsletters, unless you ask for them yourself.",
          "The basis is that you get in touch yourself and I take steps at your request before we enter into an agreement.",
        ],
      },
      {
        title: "Cookies and tracking",
        body: [
          "This site uses no tracking or analytics cookies and therefore shows no cookie banner.",
          "There is one functional cookie, sharply-lang, which remembers your language choice for a year. Your browser also remembers during your visit that you have seen the loading screen. Neither contains personal data.",
        ],
      },
      {
        title: "Who I share it with",
        body: [
          "With Resend, which sends the emails from the form, and with Vercel, where the site runs. They process data on my behalf and may do so outside the European Economic Area.",
          "I never sell your data and do not pass it on to anyone else.",
        ],
      },
      {
        title: "How long I keep it",
        body: [
          "Requests that do not lead to a project I delete within twelve months of receiving them.",
          "Data I need for the administration of a project I keep for seven years, the period the law requires.",
        ],
      },
      {
        title: "Your rights",
        body: [
          "You may see your data, have it corrected or deleted, object to the handling of it and take it with you. Email me and I will reply within four weeks.",
          "If you disagree, you can lodge a complaint with the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).",
        ],
      },
    ],
  },
  footer: {
    privacy: "Privacy",
    contactTitle: "Get started",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply is the studio of Noah Janssen, in Roermond, the Netherlands.",
    // From the Dutch trade register (sole proprietorship, head office). VAT number still to add.
    placeholders: ["Chamber of Commerce 76336840", "Scheidingsweg 2", "6045 CR Roermond"],
    socialTitle: "Follow",
    socialNote: "Channels coming soon.",
    rights: "All rights reserved.",
  },
};
