import type { Content } from "./types";

export const nl: Content = {
  meta: {
    title: "Sharply, designstudio voor merken, websites en AI-systemen",
    description:
      "Sharply ontwerpt merken en bouwt high-end websites, webshops en AI-systemen die je zelf bestuurt.",
    localeTag: "nl_NL",
  },
  nav: {
    links: [
      { href: "#studio", label: "Studio" },
      { href: "#diensten", label: "Diensten" },
      { href: "#demo", label: "Demo" },
      { href: "#werkwijze", label: "Werkwijze" },
    ],
    cta: "Start een project",
    menuOpen: "Menu openen",
    menuClose: "Menu sluiten",
    langLabel: "Taal",
  },
  hero: {
    lineOne: "Scherp ontworpen.",
    lineTwo: "Slim gebouwd.",
    body: "Wij maken merken, websites en AI-systemen voor bedrijven die niet willen lijken op de rest.",
    primary: "Start een project",
    secondary: "Bekijk de diensten",
    imageAlt:
      "Glazen bol met iridescente glans boven een blauwe horizon in een diepdonkere ruimte",
  },
  manifesto: {
    title: "De hand blijft erin",
    lead: "AI maakt het sneller. De keuzes blijven van ons.",
    body: [
      "Wij tekenen, schrijven en regisseren zelf. AI zetten wij in waar het de kwaliteit verhoogt: honderd varianten in een middag, beeld dat anders niet te betalen was, code die precies doet wat het moet doen.",
      "Wat je ziet is dus geen knop die is ingedrukt. Het is handwerk met een motor eronder.",
    ],
    imageAlt:
      "Hand die met een pen een lijn op papier tekent, waaruit blauwe lichtdraden opstijgen",
  },
  services: {
    title: "Wat we maken",
    lead: "Van een merk dat er staat tot een systeem dat blijft draaien als je slaapt.",
    items: [
      {
        key: "websites",
        title: "Websites en webapps",
        body: "Van een site die indruk maakt tot een platform met inlog, database en dashboard. Gebouwd om snel te laden en jaren mee te gaan.",
        points: ["Maatwerk ontwerp", "Database en inlog", "Zelf teksten beheren"],
        image: "/images/service-websites.webp",
        alt: "Gelaagde matglazen panelen met blauw randlicht",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "AI-chat en agents",
        body: "Een assistent in je eigen site die je klanten helpt, vragen beantwoordt, afspraken inplant en je systemen aanstuurt. Getraind op jouw informatie.",
        points: ["Getraind op je eigen content", "Plant afspraken in", "Praat met je systemen"],
        image: "/images/service-ai-chat.webp",
        alt: "Kleine glazen bol in een matglazen kaart met een lint van blauw licht",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "Webshops",
        body: "Verkopen met een winkel die aanvoelt als een merk in plaats van een template. Betalen, voorraad en verzending werken zoals je gewend bent.",
        points: ["Eigen ontwerp", "iDEAL en creditcard", "Voorraad gekoppeld"],
        image: "/images/service-webshop.webp",
        alt: "Doorschijnende glazen kubussen gestapeld als pakketten",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Koppelingen en automatisering",
        body: "Je systemen aan elkaar: agenda, mail, voorraad, facturen, CRM. Eén keer goed instellen, daarna draait het zonder jou.",
        points: ["Systemen verbonden", "Werk dat vanzelf gaat", "Rapportage die klopt"],
        image: "/images/service-integrations.webp",
        alt: "Glazen bollen verbonden door dunne lichtgevende blauwe draden",
        placeholder: true,
      },
      {
        key: "branding",
        title: "Branding en motion",
        body: "Logo, kleur, typografie en bewegend beeld. Een merk dat op elk kanaal hetzelfde klinkt, met richtlijnen waar je team mee vooruit kan.",
        points: ["Logo en huisstijl", "Merkrichtlijnen", "Animatie en video"],
        image: "/images/service-branding-motion.webp",
        alt: "Gedraaid lint van vloeibaar glas en chroom met bewegingsonscherpte",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "AI-content",
        body: "Beeld, video en animatie voor campagnes en socials. Gegenereerd waar het kan, met de hand bijgewerkt waar het telt.",
        points: ["Beeld en video", "Campagnesets", "Consistent met je merk"],
        image: "/images/service-ai-content.webp",
        alt: "Glazen prisma dat licht breekt in zwevende doorschijnende kaders",
        placeholder: true,
      },
    ],
  },
  demo: {
    title: "Zeg wat je wilt. De site past zich aan.",
    lead: "Zo werken de sites die wij bouwen: jij vraagt een wijziging, je ziet hem meteen en zet hem live. Probeer het hier.",
    note: "Dit is een demo van het idee, niet van je eigen site. Bij een echt project zit dit aan jouw content en domein vast.",
    tryTitle: "Probeer het zelf",
    tryHint: "Klik een opdracht, of typ er zelf een. Rechts zie je het meteen gebeuren.",
    inputLabel: "Of typ je eigen opdracht",
    inputPlaceholder: "Bijvoorbeeld: maak de kop groter",
    send: "Uitvoeren",
    reset: "Opnieuw",
    unknownReply:
      "Die ken ik in deze demo niet. Probeer een van de opdrachten hierboven.",
    unpublishedNote: "Nog niet gepubliceerd",
    commands: [
      {
        id: "headline",
        label: "Maak de kop groter",
        reply: "De kop staat nu een maat groter.",
      },
      {
        id: "light",
        label: "Zet hem in het licht",
        reply: "Het lichte thema staat aan.",
      },
      {
        id: "shop",
        label: "Voeg een webshop toe",
        reply: "Er staat een winkelsectie onder de kop.",
      },
      {
        id: "publish",
        label: "Publiceer",
        reply: "Gepubliceerd. De wijziging staat live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Keramiek uit Amsterdam-Noord",
      headlineBig: "Keramiek uit Amsterdam-Noord",
      body: "Kleine series, met de hand gedraaid en gestookt in eigen oven.",
      cta: "Bekijk het werk",
      shopTitle: "Nu te koop",
      shopItems: [
        { name: "Kom, gespikkeld wit", price: "48" },
        { name: "Vaas, diep blauw", price: "125" },
        { name: "Bord, zand", price: "36" },
      ],
    },
    deploy: {
      building: "Bezig met publiceren",
      live: "Live op",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "Wat je vroeg",
  },
  work: {
    title: "Werk",
    lead: "Deze plekken houden we vrij voor echte projecten.",
    body: "Sharply is net begonnen onder deze naam. Zodra de eerste projecten opgeleverd zijn, staan ze hier met beeld, aanpak en resultaat. We zetten hier geen verzonnen cases neer.",
    badge: "Nog in te vullen",
    slots: [
      { title: "Project een", discipline: "Merk en website" },
      { title: "Project twee", discipline: "Webshop" },
      { title: "Project drie", discipline: "AI-systeem" },
    ],
  },
  process: {
    title: "Hoe het gaat",
    lead: "Vier fases, van eerste gesprek tot een site die online staat.",
    steps: [
      {
        title: "Luisteren",
        body: "We beginnen met je bedrijf, je klanten en wat er nu misgaat. Daar komt een plan uit dat je begrijpt, zonder vaktaal.",
      },
      {
        title: "Ontwerpen",
        body: "Je ziet het ontwerp voordat er een regel code is. Richting, typografie, kleur en beweging, op jouw eigen content.",
      },
      {
        title: "Bouwen",
        body: "Wij bouwen het in code, niet in een bouwer. Je volgt de voortgang op een testadres en kunt elke week meekijken.",
      },
      {
        title: "Live zetten",
        body: "Wij regelen domein, hosting en snelheid. Daarna leren we je hoe je zelf aanpassingen doet, door het simpelweg te vragen.",
      },
    ],
  },
  contact: {
    title: "Vertel wat je wilt bouwen",
    lead: "Vier korte stappen. Je krijgt binnen twee werkdagen antwoord van Noah.",
    steps: [
      { title: "Wat heb je nodig", hint: "Kies alles wat van toepassing is." },
      { title: "Je project", hint: "Hoe meer je vertelt, hoe scherper ons antwoord." },
      { title: "Budget en planning", hint: "Een richting is genoeg." },
      { title: "Je gegevens", hint: "Zodat we contact kunnen opnemen." },
    ],
    needsLabel: "Waar kunnen we mee helpen",
    needs: [
      { id: "website", label: "Website of webapp" },
      { id: "webshop", label: "Webshop" },
      { id: "ai-chat", label: "AI-chat of agent" },
      { id: "automation", label: "Koppelingen en automatisering" },
      { id: "branding", label: "Branding" },
      { id: "motion", label: "Motion en video" },
      { id: "ai-content", label: "AI-content" },
      { id: "other", label: "Iets anders" },
    ],
    projectLabel: "Waar gaat het over",
    projectPlaceholder:
      "Wat voor bedrijf heb je, wat wil je bereiken en wat werkt nu niet?",
    referencesLabel: "Sites die je mooi vindt",
    referencesPlaceholder: "Plak hier links, of beschrijf de stijl die je zoekt.",
    budgetLabel: "Budget",
    budgets: [
      { id: "lt-5k", label: "Tot 5.000 euro" },
      { id: "5-15k", label: "5.000 tot 15.000 euro" },
      { id: "15-40k", label: "15.000 tot 40.000 euro" },
      { id: "gt-40k", label: "Meer dan 40.000 euro" },
      { id: "unknown", label: "Weet ik nog niet" },
    ],
    timelineLabel: "Wanneer wil je live",
    timelines: [
      { id: "asap", label: "Zo snel mogelijk" },
      { id: "quarter", label: "Binnen drie maanden" },
      { id: "half-year", label: "Binnen een half jaar" },
      { id: "exploring", label: "Ik oriënteer me nog" },
    ],
    nameLabel: "Naam",
    emailLabel: "E-mailadres",
    companyLabel: "Bedrijf",
    phoneLabel: "Telefoonnummer",
    optional: "optioneel",
    next: "Verder",
    back: "Terug",
    submit: "Aanvraag versturen",
    sending: "Versturen",
    progress: "Stap {current} van {total}",
    successTitle: "Je aanvraag is binnen",
    successBody:
      "Noah leest hem persoonlijk en antwoordt binnen twee werkdagen. Check ook je spamfolder.",
    againLabel: "Nog een aanvraag sturen",
    errorTitle: "Het versturen lukte niet",
    errorBody:
      "Probeer het opnieuw, of mail direct naar noah.janssen@sharply.nl.",
    required: "Dit veld is nog leeg",
    invalidEmail: "Controleer je e-mailadres",
    pickOne: "Kies minstens één optie",
    tooShort: "Vertel er iets meer over, minstens tien tekens",
  },
  footer: {
    contactTitle: "Aan de slag",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply, designstudio in Nederland.",
    placeholders: [
      "KVK-nummer volgt",
      "Btw-nummer volgt",
      "Adres volgt",
    ],
    socialTitle: "Volgen",
    socialNote: "Kanalen volgen binnenkort.",
    rights: "Alle rechten voorbehouden.",
  },
};
