import type { Content } from "./types";

export const nl: Content = {
  meta: {
    title: "Sharply, designstudio voor merken, websites en AI-systemen",
    description:
      "Sharply ontwerpt merken en bouwt high-end websites, webshops en AI-systemen die je zelf bestuurt.",
    localeTag: "nl_NL",
  },
  nav: {
    links: [
      { href: "#studio", label: "Studio" },
      { href: "#diensten", label: "Diensten" },
      { href: "#demo", label: "Demo" },
      { href: "#werkwijze", label: "Werkwijze" },
    ],
    cta: "Start een project",
    menuOpen: "Menu openen",
    menuClose: "Menu sluiten",
    langLabel: "Taal",
  },
  hero: {
    lineOne: "Scherp ontworpen.",
    lineTwo: "Slim gebouwd.",
    body: "Wij maken merken, websites en AI-systemen voor bedrijven die niet willen lijken op de rest.",
    primary: "Start een project",
    secondary: "Bekijk de diensten",
    imageAlt:
      "Glazen bol met iridescente glans boven een blauwe horizon in een diepdonkere ruimte",
  },
  manifesto: {
    title: "De hand blijft erin",
    lead: "AI maakt het sneller. De keuzes blijven van ons.",
    body: [
      "Wij tekenen, schrijven en regisseren zelf. AI zetten wij in waar het de kwaliteit verhoogt: honderd varianten in een middag, beeld dat anders niet te betalen was, code die precies doet wat het moet doen.",
      "Wat je ziet is dus geen knop die is ingedrukt. Het is handwerk met een motor eronder.",
    ],
    imageAlt:
      "Hand die met een pen een lijn op papier tekent, waaruit blauwe lichtdraden opstijgen",
  },
  services: {
    title: "Wat we maken",
    lead: "Van een merk dat er staat tot een systeem dat blijft draaien als je slaapt.",
    items: [
      {
        key: "websites",
        title: "Websites en webapps",
        body: "Van een site die indruk maakt tot een platform met inlog, database en dashboard. Gebouwd om snel te laden en jaren mee te gaan.",
        points: ["Maatwerk ontwerp", "Database en inlog", "Zelf teksten beheren"],
        image: "/images/service-websites.webp",
        alt: "Gelaagde matglazen panelen met blauw randlicht",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "AI-chat en agents",
        body: "Een assistent in je eigen site die je klanten helpt, vragen beantwoordt, afspraken inplant en je systemen aanstuurt. Getraind op jouw informatie.",
        points: ["Getraind op je eigen content", "Plant afspraken in", "Praat met je systemen"],
        image: "/images/service-ai-chat.webp",
        alt: "Kleine glazen bol in een matglazen kaart met een lint van blauw licht",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "Webshops",
        body: "Verkopen met een winkel die aanvoelt als een merk in plaats van een template. Betalen, voorraad en verzending werken zoals je gewend bent.",
        points: ["Eigen ontwerp", "iDEAL en creditcard", "Voorraad gekoppeld"],
        image: "/images/service-webshop.webp",
        alt: "Doorschijnende glazen kubussen gestapeld als pakketten",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Koppelingen en automatisering",
        body: "Je systemen aan elkaar: agenda, mail, voorraad, facturen, CRM. Eén keer goed instellen, daarna draait het zonder jou.",
        points: ["Systemen verbonden", "Werk dat vanzelf gaat", "Rapportage die klopt"],
        image: "/images/service-integrations.webp",
        alt: "Glazen bollen verbonden door dunne lichtgevende blauwe draden",
        placeholder: true,
      },
      {
        key: "branding",
        title: "Branding en motion",
        body: "Logo, kleur, typografie en bewegend beeld. Een merk dat op elk kanaal hetzelfde klinkt, met richtlijnen waar je team mee vooruit kan.",
        points: ["Logo en huisstijl", "Merkrichtlijnen", "Animatie en video"],
        image: "/images/service-branding-motion.webp",
        alt: "Gedraaid lint van vloeibaar glas en chroom met bewegingsonscherpte",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "AI-content",
        body: "Beeld, video en animatie voor campagnes en socials. Gegenereerd waar het kan, met de hand bijgewerkt waar het telt.",
        points: ["Beeld en video", "Campagnesets", "Consistent met je merk"],
        image: "/images/service-ai-content.webp",
        alt: "Glazen prisma dat licht breekt in zwevende doorschijnende kaders",
        placeholder: true,
      },
    ],
  },
  demo: {
    title: "Zeg wat je wilt. De site past zich aan.",
    lead: "Zo werken de sites die wij bouwen: jij vraagt een wijziging, je ziet hem meteen en zet hem live. Probeer het hier.",
    note: "Dit is een demo van het idee, niet van je eigen site. Bij een echt project zit dit aan jouw content en domein vast.",
    tryTitle: "Probeer het zelf",
    tryHint: "Klik een opdracht, of typ er zelf een. In de preview zie je het meteen gebeuren.",
    inputLabel: "Of typ je eigen opdracht",
    inputPlaceholder: "Bijvoorbeeld: maak de kop groter",
    send: "Uitvoeren",
    reset: "Opnieuw",
    unknownReply:
      "Die ken ik in deze demo niet. Probeer een van de opdrachten hierboven.",
    unpublishedNote: "Nog niet gepubliceerd",
    commands: [
      {
        id: "headline",
        label: "Maak de kop groter",
        reply: "De kop staat nu een maat groter.",
      },
      {
        id: "light",
        label: "Zet hem in het licht",
        reply: "Het lichte thema staat aan.",
      },
      {
        id: "shop",
        label: "Voeg een webshop toe",
        reply: "Er staat een winkelsectie onder de kop.",
      },
      {
        id: "publish",
        label: "Publiceer",
        reply: "Gepubliceerd. De wijziging staat live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Keramiek uit Amsterdam-Noord",
      headlineBig: "Keramiek uit Amsterdam-Noord",
      body: "Kleine series, met de hand gedraaid en gestookt in eigen oven.",
      cta: "Bekijk het werk",
      shopTitle: "Nu te koop",
      shopItems: [
        { name: "Kom, gespikkeld wit", price: "48" },
        { name: "Vaas, diep blauw", price: "125" },
        { name: "Bord, zand", price: "36" },
      ],
    },
    deploy: {
      building: "Bezig met publiceren",
      live: "Live op",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "Wat je vroeg",
  },
  work: {
    title: "Werk",
    lead: "Drie conceptprojecten die laten zien hoe wij werken.",
    body: "Dit zijn ontwerpen die wij zelf maakten om ons werk te tonen. Zodra de eerste klantprojecten live staan, komen ze hier te staan met echte resultaten.",
    conceptLabel: "Conceptproject",
    ctaTitle: "Jouw project hier?",
    ctaText: "Vertel wat je wilt bouwen, dan staat jouw werk hier straks.",
    ctaButton: "Start een project",
    items: [
      {
        key: "noordlicht",
        title: "Noordlicht Keramiek",
        discipline: "Merk en website",
        blurb:
          "Een rustige merksite voor een keramiekstudio, met verhalen uit het atelier naast de collectie.",
        image: "/images/project-noordlicht.webp",
        alt: "Laptop en telefoon met de website van een keramiekstudio in een lichte, rustige stijl",
      },
      {
        key: "halm",
        title: "Halm",
        discipline: "Webshop",
        blurb:
          "Een donkere webshop voor een huidverzorgingsmerk, gebouwd om producten als objecten te tonen.",
        image: "/images/project-halm.webp",
        alt: "Laptop en telefoon met een donkere webshop voor huidverzorging",
      },
      {
        key: "routewerk",
        title: "Routewerk",
        discipline: "AI-systeem",
        blurb:
          "Een dashboard dat zendingen volgt, vertragingen signaleert en werk vanzelf verdeelt, met een assistent erin.",
        image: "/images/project-routewerk.webp",
        alt: "Laptop met een donker dashboard met kaart, zendingen, automatisering en een AI-assistent",
      },
    ],
  },
  process: {
    title: "Hoe het gaat",
    lead: "Vier fases, van eerste gesprek tot een site die online staat.",
    steps: [
      {
        title: "Luisteren",
        body: "We beginnen met je bedrijf, je klanten en wat er nu misgaat. Daar komt een plan uit dat je begrijpt, zonder vaktaal.",
      },
      {
        title: "Ontwerpen",
        body: "Je ziet het ontwerp voordat er een regel code is. Richting, typografie, kleur en beweging, op jouw eigen content.",
      },
      {
        title: "Bouwen",
        body: "Wij bouwen het in code, niet in een bouwer. Je volgt de voortgang op een testadres en kunt elke week meekijken.",
      },
      {
        title: "Live zetten",
        body: "Wij regelen domein, hosting en snelheid. Daarna leren we je hoe je zelf aanpassingen doet, door het simpelweg te vragen.",
      },
    ],
  },
  contact: {
    title: "Vertel wat je wilt bouwen",
    lead: "Hoe meer je invult, hoe scherper ons eerste antwoord. Alleen wat gemarkeerd is moet, en je kunt altijd terug.",
    progress: "Stap {current} van {total}",
    optional: "optioneel",
    required: "Dit veld is nog leeg",
    invalidEmail: "Controleer je e-mailadres",
    invalidUrl: "Controleer de link",
    pickOne: "Kies minstens één optie",
    tooShort: "Vertel iets meer, minstens {min} tekens",
    consentRequired: "Ga hiermee akkoord om te kunnen versturen",
    next: "Verder",
    back: "Terug",
    submit: "Aanvraag versturen",
    sending: "Versturen",
    edit: "Aanpassen",
    reviewTitle: "Alles op een rij",
    reviewIntro: "Controleer je aanvraag. Klopt alles, dan gaat hij naar Noah.",
    empty: "Niet ingevuld",
    noDetails: "Voor de onderdelen die je koos hebben we geen aanvullende vragen. Ga gerust door.",
    selectPlaceholder: "Kies een optie",
    filesHint: "Maximaal 3 bestanden, samen 4 MB. PDF, afbeelding of Word.",
    filesAdd: "Bestanden toevoegen",
    filesRemove: "Verwijderen",
    filesTooBig: "Deze bestanden zijn samen groter dan 4 MB",
    filesTooMany: "Je kunt maximaal 3 bestanden meesturen",
    filesType: "Dit bestandstype accepteren we niet",
    successTitle: "Je aanvraag is binnen",
    successBody:
      "Noah leest hem persoonlijk en antwoordt binnen twee werkdagen. Check ook je spamfolder.",
    againLabel: "Nog een aanvraag sturen",
    errorTitle: "Het versturen lukte niet",
    errorBody:
      "Probeer het opnieuw, of mail direct naar noah.janssen@sharply.nl.",
    steps: [
      {
        id: "needs",
        title: "Wat je nodig hebt",
        hint: "Kies alles wat van toepassing is.",
        fields: [
          {
            id: "needs.needs",
            kind: "chips",
            multi: true,
            required: true,
            label: "Waar kunnen we mee helpen",
            options: [
              { id: "website", label: "Website of webapp" },
              { id: "webshop", label: "Webshop" },
              { id: "ai-chat", label: "AI-chat of agent" },
              { id: "automation", label: "Koppelingen en automatisering" },
              { id: "branding", label: "Branding" },
              { id: "motion", label: "Motion en video" },
              { id: "ai-content", label: "AI-content" },
              { id: "other", label: "Iets anders" },
            ],
          },
        ],
      },
      {
        id: "about",
        title: "Over jullie",
        hint: "Zodat we begrijpen voor wie we bouwen.",
        fields: [
          {
            id: "about.company",
            kind: "text",
            required: true,
            half: true,
            label: "Bedrijfsnaam",
            autoComplete: "organization",
          },
          {
            id: "about.website",
            kind: "url",
            half: true,
            label: "Huidige website",
            placeholder: "jouwbedrijf.nl",
            autoComplete: "url",
          },
          {
            id: "about.role",
            kind: "text",
            half: true,
            label: "Jouw rol",
            placeholder: "Bijvoorbeeld eigenaar of marketingmanager",
            autoComplete: "organization-title",
          },
          {
            id: "about.industry",
            kind: "select",
            half: true,
            label: "Branche",
            options: [
              { id: "retail", label: "Retail en e-commerce" },
              { id: "hospitality", label: "Horeca en toerisme" },
              { id: "health", label: "Zorg en welzijn" },
              { id: "finance", label: "Financieel en zakelijke diensten" },
              { id: "tech", label: "Software en tech" },
              { id: "education", label: "Onderwijs" },
              { id: "public", label: "Non-profit en overheid" },
              { id: "creative", label: "Creatief en media" },
              { id: "industry", label: "Industrie en logistiek" },
              { id: "other", label: "Anders" },
            ],
          },
          {
            id: "about.size",
            kind: "chips",
            label: "Hoe groot is het bedrijf",
            options: [
              { id: "solo", label: "Alleen ik" },
              { id: "2-10", label: "2 tot 10" },
              { id: "11-50", label: "11 tot 50" },
              { id: "51-250", label: "51 tot 250" },
              { id: "250+", label: "Meer dan 250" },
            ],
          },
          {
            id: "about.situation",
            kind: "chips",
            label: "Waar staan jullie nu",
            options: [
              { id: "new", label: "We beginnen helemaal nieuw" },
              { id: "old", label: "Er is iets, maar het is verouderd" },
              { id: "ok", label: "Het werkt, maar kan veel beter" },
              { id: "rebrand", label: "We zijn aan het rebranden" },
            ],
          },
        ],
      },
      {
        id: "goals",
        title: "Doel",
        hint: "Wat moet het project voor jullie doen.",
        fields: [
          {
            id: "goals.goals",
            kind: "chips",
            multi: true,
            required: true,
            label: "Wat willen jullie bereiken",
            options: [
              { id: "leads", label: "Meer aanvragen" },
              { id: "sales", label: "Online verkopen" },
              { id: "time", label: "Werk automatiseren" },
              { id: "brand", label: "Een sterker merk" },
              { id: "launch", label: "Iets nieuws lanceren" },
              { id: "replace", label: "Iets verouderds vervangen" },
              { id: "support", label: "Klanten beter helpen" },
              { id: "scale", label: "Internationaal groeien" },
            ],
          },
          {
            id: "goals.project",
            kind: "area",
            required: true,
            min: 20,
            rows: 4,
            label: "Waar gaat het over",
            placeholder:
              "Wat voor bedrijf hebben jullie, wat willen jullie bouwen en wat werkt nu niet?",
          },
          {
            id: "goals.audience",
            kind: "area",
            rows: 2,
            label: "Voor wie is het",
            placeholder: "Wie zijn je klanten en wat verwachten zij?",
          },
          {
            id: "goals.success",
            kind: "area",
            rows: 2,
            label: "Hoe weten we dat het geslaagd is",
            placeholder:
              "Bijvoorbeeld twee keer zoveel aanvragen, of tien uur per week minder handwerk.",
          },
        ],
      },
      {
        id: "details",
        title: "Details",
        hint: "Alleen vragen over wat je koos. Sla gerust over wat je nog niet weet.",
        fields: [],
      },
      {
        id: "style",
        title: "Stijl en materiaal",
        hint: "Laat ons zien wat je mooi vindt en wat je al hebt.",
        fields: [
          {
            id: "style.mood",
            kind: "chips",
            multi: true,
            label: "Welke sfeer past bij jullie",
            options: [
              { id: "minimal", label: "Rustig en minimalistisch" },
              { id: "bold", label: "Gedurfd en groot" },
              { id: "futuristic", label: "Futuristisch" },
              { id: "playful", label: "Speels" },
              { id: "editorial", label: "Editorial en verfijnd" },
              { id: "corporate", label: "Zakelijk en betrouwbaar" },
              { id: "warm", label: "Warm en menselijk" },
              { id: "dark", label: "Donker" },
              { id: "light", label: "Licht" },
            ],
          },
          {
            id: "style.references",
            kind: "area",
            rows: 3,
            label: "Sites en merken die je mooi vindt",
            placeholder: "Plak links en zeg erbij wat je er goed aan vindt.",
          },
          {
            id: "style.dislikes",
            kind: "area",
            rows: 2,
            label: "Wat wil je juist niet",
            placeholder: "Stijlen, kleuren of dingen die je bij voorbaat afwijst.",
          },
          {
            id: "style.assets",
            kind: "chips",
            multi: true,
            label: "Wat is er al",
            options: [
              { id: "logo", label: "Logo" },
              { id: "guidelines", label: "Huisstijlgids" },
              { id: "fonts", label: "Lettertypes" },
              { id: "photos", label: "Fotografie" },
              { id: "copy", label: "Teksten" },
              { id: "video", label: "Video" },
              { id: "none", label: "Nog niets" },
            ],
          },
          {
            id: "style.files",
            kind: "files",
            label: "Bijlagen",
            hint: "Een briefing, logo of voorbeeld helpt ons om sneller te antwoorden.",
          },
        ],
      },
      {
        id: "plan",
        title: "Budget en planning",
        hint: "Een richting is genoeg.",
        fields: [
          {
            id: "plan.budget",
            kind: "chips",
            required: true,
            label: "Budget",
            options: [
              { id: "lt-5k", label: "Tot 5.000 euro" },
              { id: "5-15k", label: "5.000 tot 15.000 euro" },
              { id: "15-40k", label: "15.000 tot 40.000 euro" },
              { id: "gt-40k", label: "Meer dan 40.000 euro" },
              { id: "unknown", label: "Weet ik nog niet" },
            ],
          },
          {
            id: "plan.timeline",
            kind: "chips",
            required: true,
            label: "Wanneer wil je live",
            options: [
              { id: "asap", label: "Zo snel mogelijk" },
              { id: "quarter", label: "Binnen drie maanden" },
              { id: "half-year", label: "Binnen een half jaar" },
              { id: "exploring", label: "Ik oriënteer me nog" },
            ],
          },
          {
            id: "plan.deadline",
            kind: "date",
            half: true,
            label: "Harde deadline",
            hint: "Bijvoorbeeld een lancering of evenement.",
          },
          {
            id: "plan.maintenance",
            kind: "chips",
            label: "Wie beheert het daarna",
            options: [
              { id: "self", label: "Wij zelf" },
              { id: "studio", label: "Sharply blijft ons helpen" },
              { id: "unsure", label: "Weet ik nog niet" },
            ],
          },
          {
            id: "plan.decision",
            kind: "chips",
            label: "Wie beslist",
            options: [
              { id: "me", label: "Ik beslis zelf" },
              { id: "team", label: "Een klein team" },
              { id: "board", label: "Directie of meerdere partijen" },
            ],
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        hint: "Zodat Noah kan antwoorden.",
        fields: [
          {
            id: "contact.name",
            kind: "text",
            required: true,
            half: true,
            label: "Naam",
            autoComplete: "name",
          },
          {
            id: "contact.email",
            kind: "email",
            required: true,
            half: true,
            label: "E-mailadres",
            autoComplete: "email",
          },
          {
            id: "contact.phone",
            kind: "tel",
            half: true,
            label: "Telefoonnummer",
            autoComplete: "tel",
          },
          {
            id: "contact.source",
            kind: "select",
            half: true,
            label: "Hoe kwam je bij ons uit",
            options: [
              { id: "search", label: "Zoekmachine" },
              { id: "social", label: "Social media" },
              { id: "linkedin", label: "LinkedIn" },
              { id: "referral", label: "Via iemand" },
              { id: "other", label: "Anders" },
            ],
          },
          {
            id: "contact.preferred",
            kind: "chips",
            label: "Hoe hoor je liefst van ons",
            options: [
              { id: "mail", label: "Per e-mail" },
              { id: "phone", label: "Telefonisch" },
              { id: "video", label: "Videogesprek" },
            ],
          },
          {
            id: "contact.consent",
            kind: "consent",
            required: true,
            label:
              "Ik ga ermee akkoord dat Sharply mijn gegevens gebruikt om op mijn aanvraag te reageren.",
          },
        ],
      },
      {
        id: "review",
        title: "Overzicht",
        hint: "Nog een keer controleren voor het weggaat.",
        fields: [],
      },
    ],
    detailGroups: [
      {
        need: "website",
        title: "Website of webapp",
        fields: [
          {
            id: "website.pages",
            kind: "chips",
            label: "Hoe groot wordt het",
            options: [
              { id: "1-5", label: "1 tot 5 pagina's" },
              { id: "6-15", label: "6 tot 15" },
              { id: "16-40", label: "16 tot 40" },
              { id: "40+", label: "Meer dan 40" },
              { id: "unknown", label: "Weet ik niet" },
            ],
          },
          {
            id: "website.languages",
            kind: "chips",
            multi: true,
            label: "In welke talen",
            options: [
              { id: "nl", label: "Nederlands" },
              { id: "en", label: "Engels" },
              { id: "de", label: "Duits" },
              { id: "fr", label: "Frans" },
              { id: "more", label: "Meer talen" },
            ],
          },
          {
            id: "website.editing",
            kind: "chips",
            label: "Wie past teksten aan",
            options: [
              { id: "self", label: "Wij zelf" },
              { id: "talk", label: "Door het te vragen aan de site" },
              { id: "studio", label: "Sharply" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "website.features",
            kind: "chips",
            multi: true,
            label: "Wat moet erin",
            options: [
              { id: "blog", label: "Blog of nieuws" },
              { id: "cases", label: "Portfolio of cases" },
              { id: "account", label: "Inloggen en accounts" },
              { id: "booking", label: "Afspraken of boekingen" },
              { id: "forms", label: "Slimme formulieren" },
              { id: "search", label: "Zoeken" },
              { id: "animation", label: "Geavanceerde animatie of 3D" },
              { id: "crm", label: "Koppeling met CRM of mail" },
            ],
          },
        ],
      },
      {
        need: "webshop",
        title: "Webshop",
        fields: [
          {
            id: "webshop.products",
            kind: "chips",
            label: "Hoeveel producten",
            options: [
              { id: "lt-25", label: "Tot 25" },
              { id: "25-250", label: "25 tot 250" },
              { id: "250-2500", label: "250 tot 2.500" },
              { id: "2500+", label: "Meer dan 2.500" },
            ],
          },
          {
            id: "webshop.platform",
            kind: "chips",
            label: "Bestaat er al een winkel",
            options: [
              { id: "shopify", label: "Shopify" },
              { id: "woo", label: "WooCommerce" },
              { id: "none", label: "Nog niets" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "webshop.payments",
            kind: "chips",
            multi: true,
            label: "Welke betaalmethodes",
            options: [
              { id: "ideal", label: "iDEAL" },
              { id: "cards", label: "Creditcard" },
              { id: "paypal", label: "PayPal" },
              { id: "bnpl", label: "Achteraf betalen" },
              { id: "invoice", label: "Op factuur" },
            ],
          },
          {
            id: "webshop.shipping",
            kind: "chips",
            label: "Waarheen verzenden jullie",
            options: [
              { id: "nl", label: "Alleen Nederland" },
              { id: "eu", label: "Europa" },
              { id: "world", label: "Wereldwijd" },
              { id: "digital", label: "Digitale producten" },
            ],
          },
        ],
      },
      {
        need: "ai-chat",
        title: "AI-chat of agent",
        fields: [
          {
            id: "ai-chat.channels",
            kind: "chips",
            multi: true,
            label: "Waar moet hij draaien",
            options: [
              { id: "site", label: "Op de website" },
              { id: "whatsapp", label: "WhatsApp" },
              { id: "email", label: "E-mail" },
              { id: "app", label: "In een app" },
              { id: "internal", label: "Intern voor medewerkers" },
            ],
          },
          {
            id: "ai-chat.jobs",
            kind: "chips",
            multi: true,
            label: "Wat moet hij doen",
            options: [
              { id: "faq", label: "Vragen beantwoorden" },
              { id: "booking", label: "Afspraken inplannen" },
              { id: "leads", label: "Leads kwalificeren" },
              { id: "orders", label: "Bestelstatus geven" },
              { id: "knowledge", label: "Interne kennis doorzoekbaar maken" },
            ],
          },
          {
            id: "ai-chat.sources",
            kind: "chips",
            multi: true,
            label: "Waar komt zijn kennis vandaan",
            options: [
              { id: "site", label: "Onze website" },
              { id: "docs", label: "Documenten en pdf's" },
              { id: "helpdesk", label: "Helpdesk of tickets" },
              { id: "crm", label: "CRM of database" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "ai-chat.handoff",
            kind: "chips",
            label: "Moet een mens kunnen overnemen",
            options: [
              { id: "yes", label: "Ja, naar een medewerker" },
              { id: "no", label: "Nee, volledig automatisch" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
        ],
      },
      {
        need: "automation",
        title: "Koppelingen en automatisering",
        fields: [
          {
            id: "automation.tools",
            kind: "chips",
            multi: true,
            label: "Welke systemen gebruiken jullie",
            options: [
              { id: "google", label: "Google Workspace" },
              { id: "microsoft", label: "Microsoft 365" },
              { id: "hubspot", label: "HubSpot" },
              { id: "salesforce", label: "Salesforce" },
              { id: "accounting", label: "Exact of Moneybird" },
              { id: "shop", label: "Shopify of WooCommerce" },
              { id: "chat", label: "Slack of Teams" },
              { id: "other", label: "Andere tools" },
            ],
          },
          {
            id: "automation.what",
            kind: "area",
            rows: 3,
            label: "Wat moet vanzelf gaan",
            placeholder:
              "Bijvoorbeeld: nieuwe aanvragen komen automatisch in het CRM en er staat een offerte klaar.",
          },
          {
            id: "automation.volume",
            kind: "chips",
            label: "Hoe vaak gebeurt dat",
            options: [
              { id: "weekly", label: "Enkele keren per week" },
              { id: "daily", label: "Dagelijks" },
              { id: "hundreds", label: "Honderden per dag" },
              { id: "unknown", label: "Weet ik niet" },
            ],
          },
        ],
      },
      {
        need: "branding",
        title: "Branding",
        fields: [
          {
            id: "branding.current",
            kind: "chips",
            label: "Wat is er nu",
            options: [
              { id: "none", label: "Nog niets" },
              { id: "logo", label: "Alleen een logo" },
              { id: "full", label: "Een volledige huisstijl" },
              { id: "redo", label: "Alles opnieuw" },
            ],
          },
          {
            id: "branding.deliverables",
            kind: "chips",
            multi: true,
            label: "Wat heb je nodig",
            options: [
              { id: "logo", label: "Logo" },
              { id: "colour", label: "Kleur en typografie" },
              { id: "guidelines", label: "Merkrichtlijnen" },
              { id: "templates", label: "Templates voor social en print" },
              { id: "packaging", label: "Verpakking" },
              { id: "signage", label: "Bewegwijzering of interieur" },
            ],
          },
        ],
      },
      {
        need: "motion",
        title: "Motion en video",
        fields: [
          {
            id: "motion.kinds",
            kind: "chips",
            multi: true,
            label: "Wat voor beweging",
            options: [
              { id: "logo", label: "Logo-animatie" },
              { id: "social", label: "Video voor social" },
              { id: "product", label: "Productvideo" },
              { id: "explainer", label: "Uitlegvideo" },
              { id: "web", label: "Beweging voor de website" },
            ],
          },
          {
            id: "motion.amount",
            kind: "chips",
            label: "Hoeveel",
            options: [
              { id: "one", label: "Eén stuk" },
              { id: "few", label: "Twee tot vijf" },
              { id: "series", label: "Een doorlopende serie" },
            ],
          },
        ],
      },
      {
        need: "ai-content",
        title: "AI-content",
        fields: [
          {
            id: "ai-content.kinds",
            kind: "chips",
            multi: true,
            label: "Wat voor content",
            options: [
              { id: "images", label: "Beelden" },
              { id: "video", label: "Video" },
              { id: "animation", label: "Animatie" },
              { id: "campaigns", label: "Complete campagnesets" },
            ],
          },
          {
            id: "ai-content.volume",
            kind: "chips",
            label: "Hoeveel",
            options: [
              { id: "lt-10", label: "Tot 10 stuks" },
              { id: "10-50", label: "10 tot 50" },
              { id: "50+", label: "Meer dan 50" },
              { id: "ongoing", label: "Doorlopend per maand" },
            ],
          },
        ],
      },
      {
        need: "other",
        title: "Iets anders",
        fields: [
          {
            id: "other.what",
            kind: "area",
            rows: 3,
            label: "Vertel wat je in gedachten hebt",
            placeholder: "Beschrijf het zo concreet als je kunt.",
          },
        ],
      },
    ],
  },
  footer: {
    contactTitle: "Aan de slag",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply, designstudio in Nederland.",
    placeholders: [
      "KVK-nummer volgt",
      "Btw-nummer volgt",
      "Adres volgt",
    ],
    socialTitle: "Volgen",
    socialNote: "Kanalen volgen binnenkort.",
    rights: "Alle rechten voorbehouden.",
  },
};
