import type { Content } from "./types";

export const nl: Content = {
  meta: {
    title: "Sharply | Websites van bureauniveau, door Noah Janssen",
    description:
      "Websites, webshops en AI-systemen van bureauniveau, ontworpen en gebouwd door één maker. Na oplevering pas je je site zelf aan door tegen hem te praten.",
    localeTag: "nl_NL",
  },
  nav: {
    links: [
      { href: "#studio", label: "Over mij" },
      { href: "#diensten", label: "Diensten" },
      { href: "#demo", label: "Demo" },
      { href: "#werkwijze", label: "Werkwijze" },
      { href: "#prijzen", label: "Prijzen" },
    ],
    cta: "Start een project",
    stickyButton: "Start een project",
    menuOpen: "Menu openen",
    menuClose: "Menu sluiten",
    langLabel: "Taal",
  },
  hero: {
    lineOne: "Een website van",
    lineTwo: "bureauniveau.",
    body: "Ik ontwerp en bouw hem zelf, voor ondernemers die serieus willen groeien. Je praat met mij, niet met een team. En daarna pas je hem aan door tegen hem te praten.",
    primary: "Start een project",
    secondary: "Bekijk de prijzen",
    imageAlt:
      "Glazen bol met iridescente glans boven een blauwe horizon in een diepdonkere ruimte",
  },
  manifesto: {
    title: "Bureaukwaliteit, zonder het bureau",
    lead: "Het niveau van een groot bureau, met de maker zelf aan de lijn.",
    body: [
      "Ik ben Noah. Ik ontwerp en bouw websites en AI-systemen, helemaal zelf: ontwerp, code en beeld. Zo maak ik sites op het niveau waar grote marketingbureaus mee adverteren: eigen ontwerp, eigen code, snel en tot in de details afgemaakt.",
      "Het verschil zit niet in de kwaliteit maar in de rekening. Bij een bureau betaal je accountmanagers, projectleiders, een pand en de uren van vier mensen die elkaar op de hoogte houden. Bij mij praat je met degene die het maakt, en doet AI het werk dat zich herhaalt.",
      "Ik neem bewust een beperkt aantal opdrachten tegelijk aan, zodat je mijn volle aandacht hebt. Ik werk met ondernemers die willen investeren in een site die voor ze werkt.",
    ],
    imageAlt: "Portret van Noah Janssen",
    caption: "Noah Janssen, Roermond",
  },
  services: {
    title: "Wat ik maak",
    lead: "Van een merk dat er staat tot een systeem dat blijft draaien als je slaapt.",
    items: [
      {
        key: "websites",
        title: "Een site die klanten oplevert",
        body: "Oogt je site verouderd, of levert hij te weinig aanvragen op? Ik ontwerp en bouw hem opnieuw: snel, volledig van jou, en met inlog en database als je meer nodig hebt.",
        points: ["Eigen ontwerp, geen sjabloon", "Snel op elk scherm", "Zelf teksten aanpassen"],
        image: "/images/service-websites.webp",
        alt: "Een webpagina als gelaagde glazen panelen: een menubalk, een grote kop en een rij kaarten, zwevend in diepte",
        placeholder: true,
      },
      {
        key: "aiChat",
        title: "Een assistent die je klanten helpt",
        body: "Beantwoord je elke dag dezelfde vragen? Een assistent in je eigen site doet dat voor je, plant afspraken in en kent jouw informatie.",
        points: ["Kent je eigen content", "Plant afspraken in", "Praat met je systemen"],
        image: "/images/service-ai-chat.webp",
        alt: "Glazen chatbubbels boven elkaar, waarvan er een blauw oplicht, met een glazen bol ernaast als assistent",
        placeholder: true,
      },
      {
        key: "webshop",
        title: "Een webshop die verkoopt",
        body: "Wil je online verkopen zonder dat het op een standaardwinkel lijkt? Een winkel die aanvoelt als je merk, met betalen, voorraad en verzending zoals je gewend bent.",
        points: ["Eigen ontwerp", "iDEAL en creditcard", "Voorraad gekoppeld"],
        image: "/images/service-webshop.webp",
        alt: "Drie glazen productkaarten met flessen erin, de middelste opgelicht, met een glazen winkeltas ervoor",
        placeholder: true,
      },
      {
        key: "integrations",
        title: "Minder handwerk, meer tijd",
        body: "Typ je dingen over van het ene programma naar het andere? Ik koppel agenda, mail, voorraad, facturen en CRM, zodat het vanzelf doorloopt.",
        points: ["Systemen verbonden", "Werk dat vanzelf gaat", "Rapportage die klopt"],
        image: "/images/service-integrations.webp",
        alt: "Vijf glazen app-tegels met agenda, mail, voorraad, grafiek en instellingen, verbonden met een centrale schijf door oplichtende kabels",
        placeholder: true,
      },
      {
        key: "branding",
        title: "Een merk dat blijft hangen",
        body: "Ziet je merk er overal net iets anders uit? Logo, kleur, typografie en bewegend beeld, met richtlijnen waar je team mee vooruit kan.",
        points: ["Logo en huisstijl", "Merkrichtlijnen", "Animatie en video"],
        image: "/images/service-branding-motion.webp",
        alt: "Een glazen medaillon met een beeldmerk, omringd door kleurstalen en specimenplaten, met een lint van vloeibaar glas eromheen",
        placeholder: true,
      },
      {
        key: "aiContent",
        title: "Beeld en video zonder fotoshoot",
        body: "Heb je steeds nieuw beeld nodig voor campagnes en socials? Ik maak het met AI waar dat kan, en werk het met de hand bij waar het telt.",
        points: ["Beeld en video", "Campagnesets", "Consistent met je merk"],
        image: "/images/service-ai-content.webp",
        alt: "Zwevende glazen beeldkaders met een afspeelknop, waarvan er een opbouwt uit een wolk van blauwe deeltjes",
        placeholder: true,
      },
    ],
  },
  demo: {
    title: "Je site blijft van jou. Ook na oplevering.",
    lead: "Bij elke site die ik bouw hoort een assistent die jouw site kent. Je zegt wat je wilt veranderen, je ziet het meteen, en je zet het zelf live. Geen ingewikkeld beheersysteem, geen wachten op een bureau, geen factuur voor het wijzigen van een openingstijd. Probeer het hier.",
    note: "Dit is een demo van het idee, niet van je eigen site. Bij een echt project zit dit vast aan jouw content, jouw domein en jouw huisstijl, en bepaal jij wat er wel en niet aangepast mag worden.",
    tryTitle: "Probeer het zelf",
    tryHint: "Klik een opdracht, of typ er zelf een. In de preview zie je het meteen gebeuren.",
    inputLabel: "Of typ je eigen opdracht",
    inputPlaceholder: "Bijvoorbeeld: maak de kop groter",
    send: "Uitvoeren",
    reset: "Opnieuw",
    unknownReply:
      "Die ken ik in deze demo niet. Probeer een van de opdrachten hierboven.",
    unpublishedNote: "Nog niet gepubliceerd",
    commands: [
      {
        id: "headline",
        label: "Maak de kop groter",
        reply: "De kop staat nu een maat groter.",
      },
      {
        id: "light",
        label: "Zet hem in het licht",
        reply: "Het lichte thema staat aan.",
      },
      {
        id: "shop",
        label: "Voeg een webshop toe",
        reply: "Er staat een winkelsectie onder de kop.",
      },
      {
        id: "publish",
        label: "Publiceer",
        reply: "Gepubliceerd. De wijziging staat live.",
      },
    ],
    preview: {
      brand: "Atelier Vondel",
      headline: "Keramiek uit Amsterdam-Noord",
      headlineBig: "Keramiek uit Amsterdam-Noord",
      body: "Kleine series, met de hand gedraaid en gestookt in eigen oven.",
      cta: "Bekijk het werk",
      shopTitle: "Nu te koop",
      shopItems: [
        { name: "Kom, gespikkeld wit", price: "48" },
        { name: "Vaas, diep blauw", price: "125" },
        { name: "Bord, zand", price: "36" },
      ],
    },
    deploy: {
      building: "Bezig met publiceren",
      live: "Live op",
      url: "ateliervondel.nl",
    },
    transcriptLabel: "Wat je vroeg",
  },
  work: {
    title: "Werk",
    lead: "Mijn eerste klantproject, van ontwerp tot livegang.",
    body: "Er komen binnenkort meer projecten bij.",
    conceptLabel: "Conceptproject",
    clientLabel: "Klantproject",
    ctaTitle: "Jouw project hier?",
    ctaText: "Vertel wat je wilt bouwen, dan staat jouw werk hier straks.",
    ctaButton: "Start een project",
    items: [
      {
        key: "liveweddingpaintings",
        title: "Live Wedding Paintings",
        discipline: "Merk, website en boekingen",
        blurb:
          "De site van Sara van Heukelom, die live schildert op bruiloften. Van eerste ontwerp tot boekingsformulier door mij gemaakt.",
        image: "/images/project-liveweddingpaintings.webp",
        alt: "Laptop en telefoon met de website van Live Wedding Paintings: schilderijen in gouden lijsten op een warme, lichte achtergrond",
        real: true,
      },
    ],
  },
  process: {
    title: "Hoe het gaat",
    lead: "Vier fases, van eerste gesprek tot een site die online staat.",
    steps: [
      {
        title: "Luisteren",
        body: "Ik begin met je bedrijf, je klanten en wat er nu misgaat. Daar komt een plan uit dat je begrijpt, zonder vaktaal.",
      },
      {
        title: "Ontwerpen",
        body: "Je ziet het ontwerp voordat er een regel code is. Richting, typografie, kleur en beweging, op jouw eigen content.",
      },
      {
        title: "Bouwen",
        body: "Ik bouw het in code, niet in een bouwer. Je volgt de voortgang op een testadres en kunt elke week meekijken.",
      },
      {
        title: "Live zetten",
        body: "Ik regel domein, hosting en snelheid. Daarna leer ik je hoe je zelf aanpassingen doet, door het simpelweg te vragen.",
      },
    ],
  },
  contact: {
    title: "Vertel wat je wilt bouwen",
    lead: "Beantwoord een paar vragen en je ziet aan het eind meteen een prijsindicatie. Hoe meer je invult, hoe scherper die is. Alleen wat gemarkeerd is moet, en je kunt altijd terug.",
    progress: "Stap {current} van {total}",
    optional: "optioneel",
    required: "Dit veld is nog leeg",
    invalidEmail: "Controleer je e-mailadres",
    invalidUrl: "Controleer de link",
    pickOne: "Kies minstens één optie",
    tooShort: "Vertel iets meer, minstens {min} tekens",
    consentRequired: "Ga hiermee akkoord om te kunnen versturen",
    next: "Verder",
    back: "Terug",
    submit: "Aanvraag versturen",
    sending: "Versturen",
    edit: "Aanpassen",
    reviewTitle: "Alles op een rij",
    reviewIntro: "Controleer je aanvraag. Klopt alles, dan gaat hij naar mij.",
    empty: "Niet ingevuld",
    noDetails: "Voor de onderdelen die je koos heb ik geen aanvullende vragen. Ga gerust door.",
    selectPlaceholder: "Kies een optie",
    filesHint: "Maximaal 3 bestanden, samen 4 MB. PDF, afbeelding of Word.",
    filesAdd: "Bestanden toevoegen",
    filesRemove: "Verwijderen",
    filesTooBig: "Deze bestanden zijn samen groter dan 4 MB",
    filesTooMany: "Je kunt maximaal 3 bestanden meesturen",
    filesType: "Dit bestandstype accepteer ik niet",
    successTitle: "Je aanvraag is binnen",
    successBody:
      "Ik lees hem persoonlijk en antwoord binnen twee werkdagen. Check ook je spamfolder.",
    againLabel: "Nog een aanvraag sturen",
    privacyLink: "Lees mijn privacyverklaring",
    errorTitle: "Het versturen lukte niet",
    errorBody:
      "Probeer het opnieuw, of mail direct naar noah.janssen@sharply.nl.",
    price: {
      title: "Indicatie op basis van je antwoorden",
      to: "tot",
      vat: "Bedragen zijn exclusief btw.",
      driversTitle: "Wat deze richting bepaalt",
      care: "Daarna beheer door mij, plan {plan}: {price} per maand.",
      plans: { basis: "Basis", groei: "Groei", volledig: "Volledig" },
      open: "Je koos ook iets dat niet in een formulier te vangen is, dus dat zit hier nog niet in.",
      note: "Dit is een richting, geen offerte. Na een gesprek van een half uur weet ik wat het echt wordt, en dan krijg je een vaste prijs. Past het niet bij je budget, zeg het gerust: er is bijna altijd een kleinere eerste stap.",
    },
    steps: [
      {
        id: "needs",
        title: "Wat je nodig hebt",
        hint: "Kies alles wat van toepassing is.",
        fields: [
          {
            id: "needs.needs",
            kind: "chips",
            multi: true,
            required: true,
            label: "Waar kan ik mee helpen",
            options: [
              { id: "website", label: "Een nieuwe website of webapp" },
              { id: "webshop", label: "Een webshop" },
              { id: "ai-chat", label: "Een AI-assistent voor mijn klanten" },
              { id: "automation", label: "Werk automatiseren" },
              { id: "branding", label: "Een nieuw merk of huisstijl" },
              { id: "motion", label: "Motion en video" },
              { id: "ai-content", label: "Beeld en content met AI" },
              { id: "other", label: "Iets anders" },
            ],
          },
        ],
      },
      {
        id: "about",
        title: "Over jullie",
        hint: "Zodat ik begrijp voor wie ik bouw.",
        fields: [
          {
            id: "about.company",
            kind: "text",
            required: true,
            half: true,
            label: "Bedrijfsnaam",
            autoComplete: "organization",
          },
          {
            id: "about.website",
            kind: "url",
            half: true,
            label: "Huidige website",
            placeholder: "jouwbedrijf.nl",
            autoComplete: "url",
          },
          {
            id: "about.role",
            kind: "text",
            half: true,
            label: "Jouw rol",
            placeholder: "Bijvoorbeeld eigenaar of marketingmanager",
            autoComplete: "organization-title",
          },
          {
            id: "about.industry",
            kind: "select",
            half: true,
            label: "Branche",
            options: [
              { id: "retail", label: "Retail en e-commerce" },
              { id: "hospitality", label: "Horeca en toerisme" },
              { id: "health", label: "Zorg en welzijn" },
              { id: "finance", label: "Financieel en zakelijke diensten" },
              { id: "tech", label: "Software en tech" },
              { id: "education", label: "Onderwijs" },
              { id: "public", label: "Non-profit en overheid" },
              { id: "creative", label: "Creatief en media" },
              { id: "industry", label: "Industrie en logistiek" },
              { id: "other", label: "Anders" },
            ],
          },
          {
            id: "about.size",
            kind: "chips",
            label: "Hoe groot is het bedrijf",
            options: [
              { id: "solo", label: "Alleen ik" },
              { id: "2-10", label: "2 tot 10" },
              { id: "11-50", label: "11 tot 50" },
              { id: "51-250", label: "51 tot 250" },
              { id: "250+", label: "Meer dan 250" },
            ],
          },
          {
            id: "about.situation",
            kind: "chips",
            label: "Waar staan jullie nu",
            options: [
              { id: "new", label: "We beginnen helemaal nieuw" },
              { id: "old", label: "Er is iets, maar het is verouderd" },
              { id: "ok", label: "Het werkt, maar kan veel beter" },
              { id: "rebrand", label: "We zijn aan het rebranden" },
            ],
          },
        ],
      },
      {
        id: "goals",
        title: "Doel",
        hint: "Wat moet het project voor jullie doen.",
        fields: [
          {
            id: "goals.goals",
            kind: "chips",
            multi: true,
            required: true,
            label: "Wat willen jullie bereiken",
            options: [
              { id: "leads", label: "Meer aanvragen" },
              { id: "sales", label: "Online verkopen" },
              { id: "time", label: "Werk automatiseren" },
              { id: "brand", label: "Een sterker merk" },
              { id: "launch", label: "Iets nieuws lanceren" },
              { id: "replace", label: "Iets verouderds vervangen" },
              { id: "support", label: "Klanten beter helpen" },
              { id: "scale", label: "Internationaal groeien" },
            ],
          },
          {
            id: "goals.project",
            kind: "area",
            required: true,
            min: 20,
            rows: 4,
            label: "Waar gaat het over",
            placeholder:
              "Wat voor bedrijf hebben jullie, wat willen jullie bouwen en wat werkt nu niet?",
          },
          {
            id: "goals.audience",
            kind: "area",
            rows: 2,
            label: "Voor wie is het",
            placeholder: "Wie zijn je klanten en wat verwachten zij?",
          },
          {
            id: "goals.success",
            kind: "area",
            rows: 2,
            label: "Hoe weet ik dat het geslaagd is",
            placeholder:
              "Bijvoorbeeld twee keer zoveel aanvragen, of tien uur per week minder handwerk.",
          },
        ],
      },
      {
        id: "details",
        title: "Details",
        hint: "Alleen vragen over wat je koos. Sla gerust over wat je nog niet weet.",
        fields: [],
      },
      {
        id: "style",
        title: "Stijl en materiaal",
        hint: "Laat me zien wat je mooi vindt en wat je al hebt.",
        fields: [
          {
            id: "style.mood",
            kind: "chips",
            multi: true,
            label: "Welke sfeer past bij jullie",
            options: [
              { id: "minimal", label: "Rustig en minimalistisch" },
              { id: "bold", label: "Gedurfd en groot" },
              { id: "futuristic", label: "Futuristisch" },
              { id: "playful", label: "Speels" },
              { id: "editorial", label: "Editorial en verfijnd" },
              { id: "corporate", label: "Zakelijk en betrouwbaar" },
              { id: "warm", label: "Warm en menselijk" },
              { id: "dark", label: "Donker" },
              { id: "light", label: "Licht" },
            ],
          },
          {
            id: "style.references",
            kind: "area",
            rows: 3,
            label: "Sites en merken die je mooi vindt",
            placeholder: "Plak links en zeg erbij wat je er goed aan vindt.",
          },
          {
            id: "style.dislikes",
            kind: "area",
            rows: 2,
            label: "Wat wil je juist niet",
            placeholder: "Stijlen, kleuren of dingen die je bij voorbaat afwijst.",
          },
          {
            id: "style.assets",
            kind: "chips",
            multi: true,
            label: "Wat is er al",
            options: [
              { id: "logo", label: "Logo" },
              { id: "guidelines", label: "Huisstijlgids" },
              { id: "fonts", label: "Lettertypes" },
              { id: "photos", label: "Fotografie" },
              { id: "copy", label: "Teksten" },
              { id: "video", label: "Video" },
              { id: "none", label: "Nog niets" },
            ],
          },
          {
            id: "style.files",
            kind: "files",
            label: "Bijlagen",
            hint: "Een briefing, logo of voorbeeld helpt me om sneller te antwoorden.",
          },
        ],
      },
      {
        id: "plan",
        title: "Budget en planning",
        hint: "Een richting is genoeg.",
        fields: [
          {
            id: "plan.budget",
            kind: "chips",
            required: true,
            label: "Budget",
            options: [
              { id: "lt-5k", label: "Tot 5.000 euro" },
              { id: "5-15k", label: "5.000 tot 15.000 euro" },
              { id: "15-40k", label: "15.000 tot 40.000 euro" },
              { id: "gt-40k", label: "Meer dan 40.000 euro" },
              { id: "unknown", label: "Weet ik nog niet" },
            ],
          },
          {
            id: "plan.timeline",
            kind: "chips",
            required: true,
            label: "Wanneer wil je live",
            options: [
              { id: "asap", label: "Zo snel mogelijk" },
              { id: "quarter", label: "Binnen drie maanden" },
              { id: "half-year", label: "Binnen een half jaar" },
              { id: "exploring", label: "Ik oriënteer me nog" },
            ],
          },
          {
            id: "plan.deadline",
            kind: "date",
            half: true,
            label: "Harde deadline",
            hint: "Bijvoorbeeld een lancering of evenement.",
          },
          {
            id: "plan.maintenance",
            kind: "chips",
            label: "Wie beheert het daarna",
            options: [
              { id: "self", label: "Wij zelf" },
              { id: "studio", label: "Sharply blijft ons helpen" },
              { id: "unsure", label: "Weet ik nog niet" },
            ],
          },
          {
            id: "plan.decision",
            kind: "chips",
            label: "Wie beslist",
            options: [
              { id: "me", label: "Ik beslis zelf" },
              { id: "team", label: "Een klein team" },
              { id: "board", label: "Directie of meerdere partijen" },
            ],
          },
        ],
      },
      {
        id: "contact",
        title: "Contact",
        hint: "Zodat ik kan antwoorden.",
        fields: [
          {
            id: "contact.name",
            kind: "text",
            required: true,
            half: true,
            label: "Naam",
            autoComplete: "name",
          },
          {
            id: "contact.email",
            kind: "email",
            required: true,
            half: true,
            label: "E-mailadres",
            autoComplete: "email",
          },
          {
            id: "contact.phone",
            kind: "tel",
            half: true,
            label: "Telefoonnummer",
            autoComplete: "tel",
          },
          {
            id: "contact.source",
            kind: "select",
            half: true,
            label: "Hoe kwam je bij mij uit",
            options: [
              { id: "search", label: "Zoekmachine" },
              { id: "social", label: "Social media" },
              { id: "linkedin", label: "LinkedIn" },
              { id: "referral", label: "Via iemand" },
              { id: "other", label: "Anders" },
            ],
          },
          {
            id: "contact.preferred",
            kind: "chips",
            label: "Hoe hoor je liefst van mij",
            options: [
              { id: "mail", label: "Per e-mail" },
              { id: "phone", label: "Telefonisch" },
              { id: "video", label: "Videogesprek" },
            ],
          },
          {
            id: "contact.consent",
            kind: "consent",
            required: true,
            label:
              "Ik ga ermee akkoord dat Sharply mijn gegevens gebruikt om op mijn aanvraag te reageren.",
          },
        ],
      },
      {
        id: "review",
        title: "Overzicht",
        hint: "Nog een keer controleren voor het weggaat.",
        fields: [],
      },
    ],
    detailGroups: [
      {
        need: "website",
        title: "Website of webapp",
        fields: [
          {
            id: "website.pages",
            kind: "chips",
            label: "Hoe groot wordt het",
            options: [
              { id: "1-5", label: "1 tot 5 pagina's" },
              { id: "6-15", label: "6 tot 15" },
              { id: "16-40", label: "16 tot 40" },
              { id: "40+", label: "Meer dan 40" },
              { id: "unknown", label: "Weet ik niet" },
            ],
          },
          {
            id: "website.languages",
            kind: "chips",
            multi: true,
            label: "In welke talen",
            options: [
              { id: "nl", label: "Nederlands" },
              { id: "en", label: "Engels" },
              { id: "de", label: "Duits" },
              { id: "fr", label: "Frans" },
              { id: "more", label: "Meer talen" },
            ],
          },
          {
            id: "website.editing",
            kind: "chips",
            label: "Wie past teksten aan",
            options: [
              { id: "self", label: "Wij zelf" },
              { id: "talk", label: "Door het te vragen aan de site" },
              { id: "studio", label: "Sharply" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "website.features",
            kind: "chips",
            multi: true,
            label: "Wat moet erin",
            options: [
              { id: "blog", label: "Blog of nieuws" },
              { id: "cases", label: "Portfolio of cases" },
              { id: "account", label: "Inloggen en accounts" },
              { id: "booking", label: "Afspraken of boekingen" },
              { id: "forms", label: "Slimme formulieren" },
              { id: "search", label: "Zoeken" },
              { id: "animation", label: "Geavanceerde animatie of 3D" },
              { id: "crm", label: "Koppeling met CRM of mail" },
            ],
          },
        ],
      },
      {
        need: "webshop",
        title: "Webshop",
        fields: [
          {
            id: "webshop.products",
            kind: "chips",
            label: "Hoeveel producten",
            options: [
              { id: "lt-25", label: "Tot 25" },
              { id: "25-250", label: "25 tot 250" },
              { id: "250-2500", label: "250 tot 2.500" },
              { id: "2500+", label: "Meer dan 2.500" },
            ],
          },
          {
            id: "webshop.platform",
            kind: "chips",
            label: "Bestaat er al een winkel",
            options: [
              { id: "shopify", label: "Shopify" },
              { id: "woo", label: "WooCommerce" },
              { id: "none", label: "Nog niets" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "webshop.payments",
            kind: "chips",
            multi: true,
            label: "Welke betaalmethodes",
            options: [
              { id: "ideal", label: "iDEAL" },
              { id: "cards", label: "Creditcard" },
              { id: "paypal", label: "PayPal" },
              { id: "bnpl", label: "Achteraf betalen" },
              { id: "invoice", label: "Op factuur" },
            ],
          },
          {
            id: "webshop.shipping",
            kind: "chips",
            label: "Waarheen verzenden jullie",
            options: [
              { id: "nl", label: "Alleen Nederland" },
              { id: "eu", label: "Europa" },
              { id: "world", label: "Wereldwijd" },
              { id: "digital", label: "Digitale producten" },
            ],
          },
        ],
      },
      {
        need: "ai-chat",
        title: "AI-chat of agent",
        fields: [
          {
            id: "ai-chat.channels",
            kind: "chips",
            multi: true,
            label: "Waar moet hij draaien",
            options: [
              { id: "site", label: "Op de website" },
              { id: "whatsapp", label: "WhatsApp" },
              { id: "email", label: "E-mail" },
              { id: "app", label: "In een app" },
              { id: "internal", label: "Intern voor medewerkers" },
            ],
          },
          {
            id: "ai-chat.jobs",
            kind: "chips",
            multi: true,
            label: "Wat moet hij doen",
            options: [
              { id: "faq", label: "Vragen beantwoorden" },
              { id: "booking", label: "Afspraken inplannen" },
              { id: "leads", label: "Leads kwalificeren" },
              { id: "orders", label: "Bestelstatus geven" },
              { id: "knowledge", label: "Interne kennis doorzoekbaar maken" },
            ],
          },
          {
            id: "ai-chat.sources",
            kind: "chips",
            multi: true,
            label: "Waar komt zijn kennis vandaan",
            options: [
              { id: "site", label: "Onze website" },
              { id: "docs", label: "Documenten en pdf's" },
              { id: "helpdesk", label: "Helpdesk of tickets" },
              { id: "crm", label: "CRM of database" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
          {
            id: "ai-chat.handoff",
            kind: "chips",
            label: "Moet een mens kunnen overnemen",
            options: [
              { id: "yes", label: "Ja, naar een medewerker" },
              { id: "no", label: "Nee, volledig automatisch" },
              { id: "unsure", label: "Weet ik niet" },
            ],
          },
        ],
      },
      {
        need: "automation",
        title: "Koppelingen en automatisering",
        fields: [
          {
            id: "automation.tools",
            kind: "chips",
            multi: true,
            label: "Welke systemen gebruiken jullie",
            options: [
              { id: "google", label: "Google Workspace" },
              { id: "microsoft", label: "Microsoft 365" },
              { id: "hubspot", label: "HubSpot" },
              { id: "salesforce", label: "Salesforce" },
              { id: "accounting", label: "Exact of Moneybird" },
              { id: "shop", label: "Shopify of WooCommerce" },
              { id: "chat", label: "Slack of Teams" },
              { id: "other", label: "Andere tools" },
            ],
          },
          {
            id: "automation.what",
            kind: "area",
            rows: 3,
            label: "Wat moet vanzelf gaan",
            placeholder:
              "Bijvoorbeeld: nieuwe aanvragen komen automatisch in het CRM en er staat een offerte klaar.",
          },
          {
            id: "automation.volume",
            kind: "chips",
            label: "Hoe vaak gebeurt dat",
            options: [
              { id: "weekly", label: "Enkele keren per week" },
              { id: "daily", label: "Dagelijks" },
              { id: "hundreds", label: "Honderden per dag" },
              { id: "unknown", label: "Weet ik niet" },
            ],
          },
        ],
      },
      {
        need: "branding",
        title: "Branding",
        fields: [
          {
            id: "branding.current",
            kind: "chips",
            label: "Wat is er nu",
            options: [
              { id: "none", label: "Nog niets" },
              { id: "logo", label: "Alleen een logo" },
              { id: "full", label: "Een volledige huisstijl" },
              { id: "redo", label: "Alles opnieuw" },
            ],
          },
          {
            id: "branding.deliverables",
            kind: "chips",
            multi: true,
            label: "Wat heb je nodig",
            options: [
              { id: "logo", label: "Logo" },
              { id: "colour", label: "Kleur en typografie" },
              { id: "guidelines", label: "Merkrichtlijnen" },
              { id: "templates", label: "Templates voor social en print" },
              { id: "packaging", label: "Verpakking" },
              { id: "signage", label: "Bewegwijzering of interieur" },
            ],
          },
        ],
      },
      {
        need: "motion",
        title: "Motion en video",
        fields: [
          {
            id: "motion.kinds",
            kind: "chips",
            multi: true,
            label: "Wat voor beweging",
            options: [
              { id: "logo", label: "Logo-animatie" },
              { id: "social", label: "Video voor social" },
              { id: "product", label: "Productvideo" },
              { id: "explainer", label: "Uitlegvideo" },
              { id: "web", label: "Beweging voor de website" },
            ],
          },
          {
            id: "motion.amount",
            kind: "chips",
            label: "Hoeveel",
            options: [
              { id: "one", label: "Eén stuk" },
              { id: "few", label: "Twee tot vijf" },
              { id: "series", label: "Een doorlopende serie" },
            ],
          },
        ],
      },
      {
        need: "ai-content",
        title: "AI-content",
        fields: [
          {
            id: "ai-content.kinds",
            kind: "chips",
            multi: true,
            label: "Wat voor content",
            options: [
              { id: "images", label: "Beelden" },
              { id: "video", label: "Video" },
              { id: "animation", label: "Animatie" },
              { id: "campaigns", label: "Complete campagnesets" },
            ],
          },
          {
            id: "ai-content.volume",
            kind: "chips",
            label: "Hoeveel",
            options: [
              { id: "lt-10", label: "Tot 10 stuks" },
              { id: "10-50", label: "10 tot 50" },
              { id: "50+", label: "Meer dan 50" },
              { id: "ongoing", label: "Doorlopend per maand" },
            ],
          },
        ],
      },
      {
        need: "other",
        title: "Iets anders",
        fields: [
          {
            id: "other.what",
            kind: "area",
            rows: 3,
            label: "Vertel wat je in gedachten hebt",
            placeholder: "Beschrijf het zo concreet als je kunt.",
          },
        ],
      },
    ],
  },
  pricing: {
    title: "Wat het kost",
    lead: "Bureauniveau, zonder de bureaukosten. Dit zijn de richtprijzen, zodat je niet hoeft te raden.",
    vatNote:
      "Alle bedragen zijn exclusief btw. Na een gesprek krijg je een vaste prijs, en je betaalt nooit voor wat je niet nodig hebt.",
    websitesTitle: "Websites, eenmalig",
    tiers: [
      {
        name: "Start",
        price: 3500,
        body: "Een strakke merksite die echt van jou is.",
        points: ["Tot 5 pagina's", "Eén taal", "Eigen ontwerp, geen sjabloon", "Formulier en live gezet"],
      },
      {
        name: "Studio",
        price: 6500,
        recommended: true,
        body: "Waar de meeste bedrijven op uitkomen: meer pagina's, meer beweging, twee talen.",
        points: ["Tot 12 pagina's", "Twee talen", "Animaties op maat", "Boeking of formulieren"],
      },
      {
        name: "Signature",
        price: 11500,
        from: true,
        body: "Zo uitgebreid als deze site zelf, met alles wat erbij komt kijken.",
        points: ["Eigen interacties en animaties", "Inlog en database", "Koppelingen met je systemen", "Een eigen assistent voor je klanten"],
      },
    ],
    careTitle: "Daarna blijft je site van jou",
    careLead:
      "Bij elke site hoort een assistent waarmee je zelf wijzigingen doorvoert, plus hosting en updates. Geen beheersysteem om te leren, geen tussenpersoon om te bellen.",
    plans: [
      { name: "Basis", price: 99, body: "Hosting, updates en de assistent voor kleine wijzigingen." },
      { name: "Groei", price: 199, recommended: true, body: "Meer wijzigingen, een ruimere assistent en kleine nieuwe stukken." },
      { name: "Volledig", price: 399, body: "Ook nieuwe onderdelen en koppelingen. Voor webshops en platforms." },
    ],
    perMonth: "per maand",
    from: "vanaf",
    recommended: "Aanbevolen",
    otherTitle: "Andere diensten",
    other: [
      { name: "Huisstijl", price: "€2.500 tot €6.000" },
      { name: "Webshop", price: "vanaf €9.000" },
      { name: "AI-assistent in een bestaande site", price: "vanaf €3.500" },
      { name: "Koppelingen en automatisering", price: "vanaf €2.000" },
      { name: "Motion en video", price: "vanaf €1.200" },
      { name: "AI-content", price: "vanaf €900" },
    ],
    ctaTitle: "Weet je nog niet wat jij nodig hebt?",
    ctaText: "Vul het formulier in en je ziet meteen een indicatie, op basis van je eigen antwoorden.",
    ctaButton: "Krijg een indicatie",
    ctaMail: "Liever eerst even praten? Mail me",
  },
  faq: {
    title: "Vragen die je misschien hebt",
    items: [
      {
        question: "Wat kost een website?",
        answer: "De pakketten staan hierboven en beginnen bij €3.500, exclusief btw. Na een gesprek van een half uur krijg je een vaste prijs. Is €3.500 meer dan je wilt besteden, dan ben ik niet de juiste keuze: een sjabloonsite brengt je dan sneller en goedkoper online.",
      },
      {
        question: "Hoe lang duurt het?",
        answer: "Een Start-site staat meestal binnen vier tot zes weken online, een Studio-site binnen zes tot tien. Na het eerste gesprek krijg je een planning die klopt, niet een die mooi klinkt.",
      },
      {
        question: "Van wie is de website en de code?",
        answer: "Van jou. Je krijgt de bronbestanden en je eigen hosting- en domeinaccount, zodat je nooit vastzit aan mij.",
      },
      {
        question: "Wat als ik het ontwerp niet mooi vind?",
        answer: "Je ziet het ontwerp voordat ik een regel code schrijf, en je geeft eerst akkoord. Zo bouw ik nooit op een ontwerp dat je niet wilde.",
      },
      {
        question: "Ik ben niet technisch. Kan ik hem zelf aanpassen?",
        answer: "Ja, daar is de assistent voor. Je zegt wat je wilt veranderen, zoals een tekst, een foto of een openingstijd, je ziet het meteen, en je zet het zelf live. Er is geen beheersysteem om te leren.",
      },
      {
        question: "Wie schrijft de teksten en levert de beelden?",
        answer: "Jij levert de feiten en de beelden die je hebt, ik maak er scherpe teksten van. Ontbreekt er beeld, dan maak ik het met AI of werk ik het met de hand bij.",
      },
      {
        question: "Hoe en wanneer betaal ik?",
        answer: "Een deel bij de start, de rest bij oplevering. De precieze verdeling staat in je offerte, zodat je vooraf weet waar je aan toe bent.",
      },
    ],
  },
  privacy: {
    title: "Privacyverklaring",
    updated: "Laatst bijgewerkt: 1 oktober 2026",
    sections: [
      {
        title: "Wie ik ben",
        body: [
          "Sharply is een eenmanszaak van Noah Janssen, Scheidingsweg 2, 6045 CR Roermond, KvK 76336840. Ik ben verantwoordelijk voor de verwerking van je gegevens.",
          "Vragen hierover? Mail naar noah.janssen@sharply.nl.",
        ],
      },
      {
        title: "Welke gegevens ik verwerk",
        body: [
          "Alleen wat je zelf invult in het aanvraagformulier: je naam, e-mailadres, telefoonnummer (als je dat invult), bedrijfsnaam, je antwoorden op de vragen en de bestanden die je meestuurt (maximaal drie, samen 4 MB).",
          "Mail je me rechtstreeks, dan bewaar ik die mail.",
        ],
      },
      {
        title: "Waarvoor ik ze gebruik",
        body: [
          "Om je aanvraag te beantwoorden en een offerte te maken. Niet voor reclame of nieuwsbrieven, tenzij je daar zelf om vraagt.",
          "De grondslag is dat je zelf contact opneemt en ik stappen zet op je verzoek voordat we een overeenkomst sluiten.",
        ],
      },
      {
        title: "Cookies en tracking",
        body: [
          "Deze site gebruikt geen tracking- of analysecookies en toont daarom geen cookiebanner.",
          "Er is één functioneel cookie, sharply-lang, dat een jaar je taalkeuze onthoudt. Je browser onthoudt daarnaast tijdens je bezoek dat je het laadscherm al hebt gezien. Geen van beide bevat persoonsgegevens.",
        ],
      },
      {
        title: "Met wie ik gegevens deel",
        body: [
          "Met Resend, dat de e-mails van het formulier verstuurt, en met Vercel, waar de site draait. Zij verwerken gegevens in mijn opdracht en kunnen dat buiten de Europese Economische Ruimte doen.",
          "Ik verkoop je gegevens nooit en geef ze niet door aan anderen.",
        ],
      },
      {
        title: "Hoe lang ik ze bewaar",
        body: [
          "Aanvragen die niet tot een opdracht leiden verwijder ik uiterlijk twaalf maanden na ontvangst.",
          "Gegevens die ik nodig heb voor de administratie van een opdracht bewaar ik zeven jaar, want zo lang schrijft de wet dat voor.",
        ],
      },
      {
        title: "Jouw rechten",
        body: [
          "Je mag je gegevens inzien, laten corrigeren of laten verwijderen, bezwaar maken tegen de verwerking en je gegevens meenemen. Mail me, dan reageer ik binnen vier weken.",
          "Ben je het er niet mee eens, dan kun je een klacht indienen bij de Autoriteit Persoonsgegevens.",
        ],
      },
    ],
  },
  footer: {
    privacy: "Privacy",
    contactTitle: "Aan de slag",
    email: "noah.janssen@sharply.nl",
    legalNote: "Sharply is de studio van Noah Janssen in Roermond.",
    // Uit het Handelsregister (eenmanszaak, hoofdvestiging). Btw-nummer nog toevoegen.
    placeholders: ["KvK 76336840", "Scheidingsweg 2", "6045 CR Roermond"],
    socialTitle: "Volgen",
    socialNote: "Kanalen volgen binnenkort.",
    rights: "Alle rechten voorbehouden.",
  },
};
